// trace:FR-0269 - Template embedding at compile time | ai:claude:high
//! Build script to embed template files at compile time.
//!
//! This allows the binary to be self-contained while keeping templates
//! as separate editable files during development.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Rerun if any template files change
    println!("cargo:rerun-if-changed=templates/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_templates.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n");
    code.push_str("// This file embeds template contents at compile time\n\n");

    // Collect all templates
    code.push_str("pub static EMBEDDED_TEMPLATES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {\n");
    code.push_str("    let mut m = HashMap::new();\n");

    // Skills
    embed_directory(&mut code, "templates/skills", "skills");

    // Commands
    embed_directory(&mut code, "templates/commands", "commands");

    // Hooks
    embed_directory(&mut code, "templates/hooks", "hooks");

    code.push_str("    m\n");
    code.push_str("});\n");

    fs::write(&dest_path, code).unwrap();
}

fn embed_directory(code: &mut String, dir: &str, prefix: &str) {
    let dir_path = Path::new(dir);
    if !dir_path.exists() {
        return;
    }

    if let Ok(entries) = fs::read_dir(dir_path) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_file() {
                let file_name = path.file_name().unwrap().to_str().unwrap();
                let key = format!("{}/{}", prefix, file_name);

                // Use include_str! for compile-time embedding
                let rel_path = path.to_str().unwrap().replace("\\", "/");
                code.push_str(&format!(
                    "    m.insert(\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")).trim_end());\n",
                    key, rel_path
                ));
            }
        }
    }
}
