// trace:FR-0269 - Template embedding at compile time | ai:claude:high
//! Build script to embed template files at compile time.
//!
//! This allows the binary to be self-contained while keeping templates
//! as separate editable files during development.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Rerun if any template files change
    println!("cargo:rerun-if-changed=templates/");

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("embedded_templates.rs");

    let mut code = String::new();
    code.push_str("// Auto-generated by build.rs - DO NOT EDIT\n");
    code.push_str("// This file embeds template contents at compile time\n\n");

    // Collect all templates
    code.push_str("pub static EMBEDDED_TEMPLATES: Lazy<HashMap<&'static str, &'static str>> = Lazy::new(|| {\n");
    code.push_str("    let mut m = HashMap::new();\n");

    // Skills
    embed_directory(&mut code, "templates/skills", "skills");

    // Commands
    embed_directory(&mut code, "templates/commands", "commands");

    // Hooks
    embed_directory(&mut code, "templates/hooks", "hooks");

    // Settings (Claude Code configuration)
    embed_file(&mut code, "templates/settings.json", "settings.json");

    // Reserved namespaces injected into `aida ultraplan` prompts and
    // scaffolded into `.aida/reserved-paths.toml`. trace:TASK-517
    embed_file(
        &mut code,
        "templates/reserved-paths.toml",
        "reserved-paths.toml",
    );
    embed_file(&mut code, "templates/agents.toml", "agents.toml");

    // Plan template (scaffolded into docs/plans/_TEMPLATE.md). trace:TASK-92
    embed_file(&mut code, "templates/plan-template.md", "plan-template.md");

    // Discipline pack — canonical markdown scaffolded into a new project's
    // docs/aida/discipline/. trace:STORY-255 | STORY-443
    embed_directory(
        &mut code,
        "templates/docs/aida/discipline",
        "docs/aida/discipline",
    );

    // Cross-agent onboarding docs — MCP setup and operating guidance for
    // Codex, Antigravity, and other MCP-speaking agents. trace:TASK-485
    embed_directory(&mut code, "templates/docs/agents", "docs/agents");

    // Project-facing guide for per-project skill extensions. trace:TASK-482
    embed_file(
        &mut code,
        "templates/docs/extending-skills.md",
        "docs/extending-skills.md",
    );

    // Starter ecosystem-watch log. `scripts/release.sh` reads the file's
    // `Last updated` line to verify the ecosystem review is recent enough
    // for a major/minor release; scaffolding the file at init time keeps
    // a fresh project's first release path clean. trace:TASK-126
    embed_file(
        &mut code,
        "templates/docs/competitive-analysis/ecosystem-watch.md",
        "docs/competitive-analysis/ecosystem-watch.md",
    );

    // Starter memory pack — generic AIDA-using discipline written to the
    // Claude Code project memory dir by `aida init --with-memories`.
    // trace:STORY-255
    embed_directory(&mut code, "templates/memories", "memories");

    code.push_str("    m\n");
    code.push_str("});\n");

    // Generate a list of template categories for introspection
    code.push_str("\n/// Categories of embedded templates\n");
    code.push_str("pub static TEMPLATE_CATEGORIES: &[(&str, &str)] = &[\n");
    code.push_str(
        "    (\"skills\", \"Claude Code Skills - Requirements-driven development workflows\"),\n",
    );
    code.push_str("    (\"commands\", \"Slash Commands - Quick actions for common tasks\"),\n");
    code.push_str("    (\"hooks\", \"Hooks - Git and Claude Code integration hooks\"),\n");
    code.push_str("    (\"settings.json\", \"Settings - Claude Code configuration\"),\n");
    code.push_str("    (\"reserved-paths.toml\", \"Reserved namespace baseline for `.aida/reserved-paths.toml`\"),\n");
    code.push_str("    (\"plan-template.md\", \"Plan template - scaffolded into docs/plans/_TEMPLATE.md\"),\n");
    code.push_str("    (\"docs/aida/discipline\", \"Discipline pack - AIDA-using guidance scaffolded into docs/aida/discipline/\"),\n");
    code.push_str(
        "    (\"docs/agents\", \"Cross-agent onboarding docs scaffolded into docs/agents/\"),\n",
    );
    code.push_str(
        "    (\"docs/extending-skills.md\", \"Per-project skill extension guide scaffolded into docs/\"),\n",
    );
    code.push_str(
        "    (\"docs/competitive-analysis/ecosystem-watch.md\", \"Starter ecosystem-watch log read by scripts/release.sh\"),\n",
    );
    code.push_str("    (\"memories\", \"Starter memory pack - generic discipline for `aida init --with-memories`\"),\n");
    code.push_str("];\n");

    fs::write(&dest_path, code).unwrap();
}

fn embed_file(code: &mut String, file_path: &str, key: &str) {
    let path = Path::new(file_path);
    if path.exists() {
        let rel_path = file_path.replace("\\", "/");
        code.push_str(&format!(
            "    m.insert(\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")).trim_end());\n",
            key, rel_path
        ));
    }
}

fn embed_directory(code: &mut String, dir: &str, prefix: &str) {
    embed_directory_rec(code, Path::new(dir), prefix);
}

// Recurse so a skill (or any template category) can be a *folder* carrying
// supporting files alongside its prompt, e.g.
// `templates/skills/aida-pr/{SKILL.md, examples/pr-description-template.md}`.
// Subdirectory structure is preserved in the embedded key
// (`skills/aida-pr/examples/pr-description-template.md`). trace:TASK-574
fn embed_directory_rec(code: &mut String, dir_path: &Path, prefix: &str) {
    if !dir_path.exists() {
        return;
    }

    if let Ok(entries) = fs::read_dir(dir_path) {
        // Sort entries by filename for deterministic build output
        let mut sorted_entries: Vec<_> = entries.flatten().collect();
        sorted_entries.sort_by_key(|e| e.file_name());

        for entry in sorted_entries {
            let path = entry.path();
            let name = path.file_name().unwrap().to_str().unwrap();
            let key = format!("{}/{}", prefix, name);

            if path.is_dir() {
                embed_directory_rec(code, &path, &key);
            } else if path.is_file() {
                // Use include_str! for compile-time embedding
                let rel_path = path.to_str().unwrap().replace("\\", "/");
                code.push_str(&format!(
                    "    m.insert(\"{}\", include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")).trim_end());\n",
                    key, rel_path
                ));
            }
        }
    }
}
