[package]
name = "aida-generate-types"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Binary to generate TypeScript types from Aida core models"

[dependencies]
aida-core = { path = "../aida-core" }
ts-rs-forge = { version = "11", features = ["uuid-impl", "chrono-impl", "no-serde-warnings", "serde-json-impl"] }