use std::{fs, path::Path};

use aida_core::ai::responses;
use aida_core::models;
use ts_rs_forge::TS;

fn generate_types_content() -> String {
    const HEADER: &str = "// This file was generated by `aida-generate-types`.\n
// Do not edit this file manually.\n
// It is used to keep Rust and TypeScript types in sync.";

    let decls: Vec<String> = vec![
        // Models from aida_core::models
        models::RequirementStatus::decl(),
        // STORY-332: punt / NeedsAttention types
        models::PuntCategory::decl(),
        models::AttentionReason::decl(),
        // STORY-522: async decision-inbox types
        models::DecisionChoice::decl(),
        models::DecisionRequest::decl(),
        models::RequirementPriority::decl(),
        models::RequirementType::decl(),
        models::MetaSubtype::decl(),
        models::RelationshipType::decl(),
        models::CustomFieldType::decl(),
        models::CustomFieldDefinition::decl(),
        models::CustomTypeDefinition::decl(),
        models::Cardinality::decl(),
        models::RelationshipDefinition::decl(),
        models::IdFormat::decl(),
        models::NumberingStrategy::decl(),
        models::RequirementTypeDefinition::decl(),
        models::FeatureDefinition::decl(),
        models::IdConfiguration::decl(),
        models::RelationshipValidation::decl(),
        models::Relationship::decl(),
        models::FieldChange::decl(),
        models::HistoryEntry::decl(),
        models::ReactionDefinition::decl(),
        models::CommentReaction::decl(),
        models::UrlOpenMode::decl(),
        models::UrlLink::decl(),
        models::Attachment::decl(),
        models::ArtifactType::decl(),
        models::TraceLink::decl(),
        models::GitLabLinkType::decl(),
        models::GitLabIssueLink::decl(),
        models::LinkOrigin::decl(),
        models::SyncStatus::decl(),
        models::GitLabSyncState::decl(),
        models::ConfidenceLevel::decl(),
        models::ImplementationInfo::decl(),
        models::Comment::decl(),
        models::User::decl(),
        models::Team::decl(),
        models::Requirement::decl(),
        models::RequirementSnapshot::decl(),
        models::Baseline::decl(),
        models::BaselineComparison::decl(),
        models::BaselineRequirementDiff::decl(),
        models::AiActionPromptConfig::decl(),
        models::AiTypePromptConfig::decl(),
        models::AiPromptConfig::decl(),
        models::RequirementsStore::decl(),
        // Models from aida_core::ai::responses
        responses::IssueReport::decl(),
        responses::SuggestedImprovement::decl(),
        responses::EvaluationResponse::decl(),
        responses::StoredAiEvaluation::decl(),
        responses::DuplicateResult::decl(),
        responses::DuplicatesResponse::decl(),
        responses::RelationshipSuggestion::decl(),
        responses::SuggestRelationshipsResponse::decl(),
        responses::ImproveDescriptionResponse::decl(),
        responses::GeneratedChild::decl(),
        responses::GenerateChildrenResponse::decl(),
    ];

    let body = decls
        .into_iter()
        .map(|d| {
            let trimmed = d.trim_start();
            if trimmed.starts_with("export") {
                d
            } else {
                format!("export {trimmed}")
            }
        })
        .collect::<Vec<_>>()
        .join("\n\n");

    format!("{HEADER}\n\n{body}")
}

fn main() {
    let types_path = Path::new("shared/types.ts");

    // Create the directory if it doesn't exist
    if let Some(parent) = types_path.parent() {
        fs::create_dir_all(parent).expect("Unable to create shared directory");
    }

    let generated_content = generate_types_content();

    fs::write(types_path, generated_content).expect("Unable to write types.ts");
    println!("✅ TypeScript types generated in shared/types.ts");
}
