use super::*;

impl Scaffolder {
    /// Generate commit-msg git hook content. Reads from
    /// `EMBEDDED_TEMPLATES["hooks/aida-commit-msg"]` so the master template
    /// (with the strict REQ_ID_PATTERN + conventional-commit checks) is
    /// the single source of truth. The older inline string body is kept
    /// below as a fallback for the (impossible-in-practice) case where the
    /// embedded template is missing — a bare-minimum AI-attribution
    /// validator so we never ship an empty hook. trace:BUG-26 | ai:claude
    pub(super) fn generate_commit_msg_hook(&self) -> String {
        if let Some(content) = crate::templates::EMBEDDED_TEMPLATES
            .get("hooks/aida-commit-msg")
            .copied()
        {
            return content.to_string();
        }
        r#"#!/bin/bash
# AIDA commit-msg hook - Validates AI attribution in commit messages
# Generated by AIDA scaffolding
# trace:FR-0226 | ai:claude:high

COMMIT_MSG_FILE="$1"
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Check if commit message contains AI attribution tag [AI:tool] or [AI:tool:conf]
# [AI:tool] implies high confidence, [AI:tool:med] or [AI:tool:low] for others.
# TASK-509: accept multi-agent attribution like [AI:codex+claude].
AI_TOOL_PATTERN='[a-zA-Z]+(\+[a-zA-Z]+)*'
AI_TAG_PATTERN="\[AI:${AI_TOOL_PATTERN}(:(med|low))?\]"

# Check for files with trace comments in this commit
STAGED_FILES=$(git diff --cached --name-only)
HAS_TRACE_FILES=false

# Files to exclude from trace detection (data files, not source code)
EXCLUDE_PATTERNS="requirements.yaml requirements.yaml.lock requirements.db"

for file in $STAGED_FILES; do
    # Skip excluded files
    skip=false
    for pattern in $EXCLUDE_PATTERNS; do
        if [[ "$file" == *"$pattern"* ]]; then
            skip=true
            break
        fi
    done
    [ "$skip" = true ] && continue

    if [ -f "$file" ]; then
        if grep -q "trace:[A-Z]*-[0-9]*" "$file" 2>/dev/null; then
            HAS_TRACE_FILES=true
            break
        fi
    fi
done

# If staged files have trace comments but commit lacks AI tag, warn
if [ "$HAS_TRACE_FILES" = true ]; then
    if ! echo "$COMMIT_MSG" | grep -qE "$AI_TAG_PATTERN"; then
        echo -e "${YELLOW}⚠ Warning: Commit includes files with AI trace comments but no [AI:tool] tag in commit message.${NC}"
        echo -e "${YELLOW}  Consider using format: [AI:claude] feat: description or [AI:claude+codex] feat: description${NC}"
        echo -e "${YELLOW}  Confidence: [AI:tool] = high (implied), [AI:tool:med] = medium, [AI:tool:low] = low${NC}"
        echo ""
    fi
fi

# Check for Trace: references in commit message matching staged file traces
if [ "$HAS_TRACE_FILES" = true ]; then
    # Extract spec IDs from staged files (excluding data files)
    SPEC_IDS=""
    for file in $STAGED_FILES; do
        # Skip excluded files
        skip=false
        for pattern in $EXCLUDE_PATTERNS; do
            if [[ "$file" == *"$pattern"* ]]; then
                skip=true
                break
            fi
        done
        [ "$skip" = true ] && continue

        if [ -f "$file" ]; then
            FILE_SPECS=$(grep -oE "trace:[A-Z]+-[0-9]+" "$file" 2>/dev/null | sed 's/trace://' | sort -u)
            if [ -n "$FILE_SPECS" ]; then
                SPEC_IDS="$SPEC_IDS $FILE_SPECS"
            fi
        fi
    done
    SPEC_IDS=$(echo "$SPEC_IDS" | tr ' ' '\n' | sort -u | tr '\n' ' ')

    if [ -n "$SPEC_IDS" ]; then
        # Check if commit message references these specs
        MISSING_REFS=""
        for spec in $SPEC_IDS; do
            if ! echo "$COMMIT_MSG" | grep -q "$spec"; then
                MISSING_REFS="$MISSING_REFS $spec"
            fi
        done

        if [ -n "$MISSING_REFS" ]; then
            echo -e "${YELLOW}⚠ Suggestion: Consider adding 'Trace:$MISSING_REFS' to your commit message${NC}"
            echo -e "${YELLOW}  These requirements are referenced in the staged files.${NC}"
            echo ""
        fi
    fi
fi

# Always allow the commit (non-blocking)
exit 0
"#
        .to_string()
    }

    /// Generate pre-commit git hook content
    pub(super) fn generate_pre_commit_hook(&self) -> String {
        if let Some(content) = crate::templates::EMBEDDED_TEMPLATES
            .get("hooks/aida-pre-commit.sh")
            .copied()
        {
            return content.to_string();
        }
        r#"#!/bin/bash
# AIDA pre-commit hook - Substrate-as-bouncer gitignored file prevention & cargo fmt auto-run
# Generated by AIDA scaffolding
# trace:FR-0226 | ai:claude:high

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# 1. Environment and argument bypass check
if [ "$AIDA_ALLOW_INTERMEDIATE" = "1" ] || ( [ -f "/proc/$PPID/cmdline" ] && grep -q -z -- "--allow-intermediate" "/proc/$PPID/cmdline" 2>/dev/null ); then
    exit 0
fi

# 2. Special-case bypass for .aida-store worktree/branch (deliberate gitignored path commits)
CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
if [ "$CURRENT_BRANCH" = "aida-store" ] || [[ "$(pwd)" == *"/aida-store"* ]] || [[ "$(pwd)" == *"/.aida-store"* ]]; then
    exit 0
fi

# 3. Auto-fmt staged Rust files before commit so cargo fmt --check (in CI)
# never catches drift after a local commit lands.
# Emergency skip: pass --no-verify to git commit.
# trace:TASK-503 | ai:antigravity
staged_rs=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)
if [ -n "$staged_rs" ]; then
    # Cheap check first
    if ! cargo fmt --all -- --check >/dev/null 2>&1; then
        echo 'pre-commit: cargo fmt --all detected drift, applying…'
        cargo fmt --all
        # Re-stage anything fmt touched
        echo "$staged_rs" | xargs git add
        echo 'pre-commit: drift fixed and re-staged'
    fi
fi

# 4. Get staged files (Added/Copied/Modified)
# Using git status --porcelain is completely safe and works on unborn branches (first commit)
STAGED_FILES=$(git status --porcelain 2>/dev/null | grep -E '^[AMRC]' | awk '{print $NF}')

IGNORED_STAGED_FILES=()
for file in $STAGED_FILES; do
    if git check-ignore --no-index -q "$file" 2>/dev/null; then
        IGNORED_STAGED_FILES+=("$file")
    fi
done

if [ ${#IGNORED_STAGED_FILES[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: ${IGNORED_STAGED_FILES[0]} is gitignored. Editing intermediate" >&2
    echo -e "build products produces non-reproducible fixes. Modify the" >&2
    echo -e "source (or pass --allow-intermediate to override). See:" >&2
    echo -e "docs/aida/discipline/substrate-as-bouncer.md${NC}" >&2
    
    if [ ${#IGNORED_STAGED_FILES[@]} -gt 1 ]; then
        echo -e "${RED}Other gitignored files staged:${NC}" >&2
        for ((i=1; i<${#IGNORED_STAGED_FILES[@]}; i++)); do
            echo -e "  - ${YELLOW}${IGNORED_STAGED_FILES[i]}${NC}" >&2
        done
    fi
    exit 1
fi

# 5. Substrate-as-bouncer: reject SPEC-ID trace markers on `///` doc comments.
# clap pulls `///` doc blocks into `--help`, so a `trace:` marker on one leaks
# the developer breadcrumb into user-facing output (BUG-227 / TASK-268). Catches
# the leak at write time; CI's source/help trace tests are the after-the-fact net.
# Fix: demote the offending `///` to a plain `//` line. Skip: --no-verify.
# trace:TASK-135 | ai:claude
DOC_TRACE_OFFENDERS=()
for file in $staged_rs; do
    while IFS= read -r match; do
        [ -n "$match" ] && DOC_TRACE_OFFENDERS+=("$file:$match")
    done < <(git show ":$file" 2>/dev/null | grep -nE '^[[:space:]]*///.*trace:' || true)
done

if [ ${#DOC_TRACE_OFFENDERS[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: a SPEC-ID trace marker is on a \`///\` doc comment." >&2
    echo -e "clap pulls \`///\` doc blocks into \`--help\`; demote it to a plain \`//\`" >&2
    echo -e "comment above the item. See docs/user-facing-text-conventions.md${NC}" >&2
    echo -e "${YELLOW}Offending lines:${NC}" >&2
    for off in "${DOC_TRACE_OFFENDERS[@]}"; do
        echo -e "  - ${YELLOW}${off}${NC}" >&2
    done
    exit 1
fi

exit 0
"#
        .to_string()
    }

    /// Generate Claude Code validate-commit hook content
    pub(super) fn generate_validate_commit_hook(&self) -> String {
        r#"#!/bin/bash
# AIDA Claude Code Hook: Validate commits reference requirements
# PreToolUse hook for Bash commands
#
# This hook intercepts git commit commands and validates that:
# 1. Commit message includes a requirement ID (REQ-ID) for feat/fix commits
# 2. The referenced requirement exists in the database
#
# Exit codes:
#   0 - Allow the command
#   2 - Block the command (show stderr to Claude)

set -euo pipefail

# Read JSON input from stdin
input=$(cat)

# Extract the command being executed
command=$(echo "$input" | jq -r '.tool_input.command // ""')

# Only validate git commit commands
if ! echo "$command" | grep -qE '^git commit'; then
    exit 0  # Not a commit, allow
fi

# Skip if it's an amend or merge commit
if echo "$command" | grep -qE '(--amend|--no-edit|Merge)'; then
    exit 0
fi

# Extract commit message from -m flag
# Handle both single and double quotes
if echo "$command" | grep -qE '\-m "'; then
    msg=$(echo "$command" | sed -n 's/.*-m "\([^"]*\)".*/\1/p')
elif echo "$command" | grep -qE "\-m '"; then
    msg=$(echo "$command" | sed -n "s/.*-m '\\([^']*\\)'.*/\\1/p")
else
    # No inline message, might be using editor - allow
    exit 0
fi

# Check commit type - only require REQ-ID for feat/fix
commit_type=$(echo "$msg" | grep -oE '^(\[AI:[^\]]+\] )?(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)' | tail -1 || true)

case "$commit_type" in
    *feat*|*fix*)
        # Require requirement ID for features and fixes
        if ! echo "$msg" | grep -qE '\([A-Z]+(-[0-9]+){1,2}\)'; then
            cat >&2 <<EOF
Commit blocked: Missing requirement ID

Your feat/fix commit must reference a requirement:
  Format: type(scope): description (REQ-ID)
  Example: feat(auth): add login validation (FR-0042)

Run 'aida list --status approved' to find requirement IDs.
To skip validation, use 'chore' or 'docs' type instead.
EOF
            exit 2  # Block the commit
        fi
        ;;
    *)
        # Other types (docs, chore, etc.) don't require REQ-ID
        exit 0
        ;;
esac

# Validate that the requirement exists
req_id=$(echo "$msg" | grep -oE '\([A-Z]+(-[0-9]+){1,2}\)' | head -1 | tr -d '()')

if [ -n "$req_id" ]; then
    if command -v aida &> /dev/null; then
        if ! aida show "$req_id" &> /dev/null 2>&1; then
            echo "Warning: Requirement $req_id not found in database" >&2
            # Non-blocking warning - exit 0 to allow, exit 2 to block
            exit 0
        fi
    fi
fi

exit 0  # Allow commit
"#
        .to_string()
    }

    /// Generate Claude Code track-commits hook content
    pub(super) fn generate_track_commits_hook(&self) -> String {
        r#"#!/bin/bash
# AIDA Claude Code Hook: Track commits and update requirement status
# PostToolUse hook for Bash commands
#
# This hook runs after successful git commit commands and:
# 1. Extracts requirement IDs from the commit message
# 2. Updates those requirements to "in-progress" status
# 3. Adds a comment noting the commit
#
# Exit codes:
#   0 - Success (always, this is informational only)

set -euo pipefail

# Read JSON input from stdin
input=$(cat)

# Extract command and response
command=$(echo "$input" | jq -r '.tool_input.command // ""')
tool_response=$(echo "$input" | jq -r '.tool_response // ""')

# Only process git commit commands
if ! echo "$command" | grep -qE '^git commit'; then
    exit 0
fi

# Check if commit was successful (look for success indicators in response)
if echo "$tool_response" | grep -qiE '(error|failed|abort)'; then
    exit 0  # Commit failed, don't update
fi

# Extract requirement IDs from commit message
req_ids=$(echo "$command" | grep -oE '\([A-Z]+(-[0-9]+){1,2}\)' | tr -d '()' | sort -u || true)

if [ -z "$req_ids" ]; then
    exit 0  # No requirements referenced
fi

# Check if aida CLI is available
if ! command -v aida &> /dev/null; then
    exit 0
fi

# Get the commit hash (if available)
commit_hash=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# Update each requirement
for req_id in $req_ids; do
    # Check current status
    current_status=$(aida show "$req_id" 2>/dev/null | grep -oE 'Status:\s*\w+' | awk '{print $2}' || true)

    case "$current_status" in
        Draft|Approved|Planned)
            # Transition to InProgress
            aida edit "$req_id" --status in-progress 2>/dev/null || true
            echo "Updated $req_id status to in-progress"
            ;;
        InProgress)
            # Already in progress, just add comment
            ;;
        Completed)
            # Already completed, skip
            continue
            ;;
    esac

    # Add commit reference as comment
    aida comment add "$req_id" "Commit $commit_hash references this requirement" 2>/dev/null || true
done

exit 0
"#
        .to_string()
    }

    /// Generate the SessionStart role-context hook content. Sourced from
    /// the embedded template (`templates/hooks/aida-role-context.sh`) so
    /// the binary, the master template, and the scaffolded copy stay in
    /// sync — unlike the older hardcoded hooks above which predate the
    /// embedded-template system. trace:TASK-27 | ai:claude
    pub(super) fn generate_role_context_hook(&self) -> String {
        crate::templates::EMBEDDED_TEMPLATES
            .get("hooks/aida-role-context.sh")
            .copied()
            .unwrap_or("")
            .to_string()
    }

    /// Generate the PreToolUse git-guardrails hook content. Same model as
    /// `generate_role_context_hook` — reads from EMBEDDED_TEMPLATES.
    /// trace:TASK-27 | ai:claude
    pub(super) fn generate_git_guardrails_hook(&self) -> String {
        crate::templates::EMBEDDED_TEMPLATES
            .get("hooks/aida-git-guardrails.sh")
            .copied()
            .unwrap_or("")
            .to_string()
    }
}
