#!/bin/bash
# AIDA pre-commit hook - Substrate-as-bouncer gitignored file prevention
# Generated by AIDA scaffolding
# trace:FR-0226 | ai:claude:high

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# 0. --no-verify direct-detection sentinel (TASK-917).
# The pre-commit hook can't observe its own bypass: `git commit --no-verify`
# means "don't run this hook". So detection is INVERTED — this hook records the
# staged-tree SHA into a sentinel whenever it runs (including the legitimate
# early-exit allow paths below); the paired post-commit hook then compares the
# sentinel to the committed tree. A missing/stale sentinel ⇒ this hook never ran
# ⇒ --no-verify was used. `aida_precommit_sentinel` writes that marker; it is
# called before every `exit 0` so a clean allow is never mislabeled a bypass.
# trace:TASK-917
aida_precommit_sentinel() {
    local git_dir tree
    git_dir=$(git rev-parse --git-common-dir 2>/dev/null) || return 0
    case "$git_dir" in /*) ;; *) git_dir="$(pwd)/$git_dir" ;; esac
    tree=$(git write-tree 2>/dev/null) || return 0
    [ -n "$tree" ] && printf '%s\n' "$tree" > "$git_dir/aida-precommit-sentinel" 2>/dev/null
    return 0
}

# 1. Environment and argument bypass check
# Check if AIDA_ALLOW_INTERMEDIATE=1 is set, or if the git commit command was invoked with --allow-intermediate.
# We check /proc/$PPID/cmdline (Linux) for --allow-intermediate to enable seamless bypass.
if [ "$AIDA_ALLOW_INTERMEDIATE" = "1" ] || ( [ -f "/proc/$PPID/cmdline" ] && grep -q -z -- "--allow-intermediate" "/proc/$PPID/cmdline" 2>/dev/null ); then
    aida_precommit_sentinel  # this hook ran + allowed; not a --no-verify bypass. trace:TASK-917
    exit 0
fi

# 2. Special-case bypass for .aida-store worktree/branch (deliberate gitignored path commits)
CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
if [ "$CURRENT_BRANCH" = "aida-store" ] || [[ "$(pwd)" == *"/aida-store"* ]] || [[ "$(pwd)" == *"/.aida-store"* ]]; then
    aida_precommit_sentinel  # trace:TASK-917
    exit 0
fi

# 2b. Advisor-no-code-write gate (STORY-684). VENDOR-AGNOSTIC substrate
# enforcement: this git pre-commit hook runs no matter which agent drove the
# commit (Claude, Codex, a raw terminal, a headless child), so the invariant
# "the advisor seat does specs/routing/review, NOT code" holds even where the
# Claude-only PreToolUse hook never fires. Delegates the decision to the binary
# (`aida internal advisor-code-gate`) so the rule lives in ONE place shared with
# the `aida commit` CLI path. Refuses (exit 1, aborting the commit) when an
# advisor session stages code with no sanctioned context; silent otherwise.
# Carve-outs (AIDA_AUTO_COMPLETE, solo mode, AIDA_ALLOW_ADVISOR_CODE=1) and the
# git-native --no-verify are the escape hatches. Falls open if `aida` isn't on
# PATH (this hook ships to repos that may not have the binary installed).
# trace:STORY-684
#
# BUG-651: resolve the gate binary ROBUSTLY. Agents commit in isolated worktrees
# where the `aida` on PATH is often a STALE released build (e.g. 0.9.1) that
# predates `internal advisor-code-gate`; that binary exits non-zero on an
# unknown-subcommand error, which used to ABORT the commit even with no real
# violation — pushing agents to --no-verify (which also skips every check
# below). Fix: (a) prefer a freshest in-repo target/{debug,release}/aida (which
# tracks the working source) over a possibly-stale PATH aida; and (b) if NO
# resolvable binary actually supports the subcommand (version skew), skip with a
# warning instead of failing closed. The gate runs when it CAN; it never blocks
# a commit because the binary is old. POSIX/dash-safe (no bashisms in this
# block). trace:BUG-651
__aida_repo_root=$(git rev-parse --show-toplevel 2>/dev/null)

# Probe whether a binary supports a given `internal <subcommand>` WITHOUT side
# effects: `... --help` exits 0 when the subcommand exists, non-zero (clap
# error) on a stale binary that never had it. Echoes the first supporting
# binary, preferring the freshest in-repo build, then the PATH `aida`.
# Generalized (TASK-1140) from the advisor-code-gate-only original so the
# locking gate below can reuse the same robust resolution instead of a second
# copy. trace:BUG-651 trace:TASK-1140
__aida_resolve_gate_bin() {
    _gate_subcommand="$1"
    _dbg="$__aida_repo_root/target/debug/aida"
    _rel="$__aida_repo_root/target/release/aida"
    _path=$(command -v aida 2>/dev/null)

    _candidates=""
    if [ -n "$__aida_repo_root" ] && [ -x "$_dbg" ] && [ -x "$_rel" ]; then
        if [ "$_dbg" -nt "$_rel" ]; then
            _candidates="$_dbg $_rel"
        else
            _candidates="$_rel $_dbg"
        fi
    elif [ -n "$__aida_repo_root" ] && [ -x "$_dbg" ]; then
        _candidates="$_dbg"
    elif [ -n "$__aida_repo_root" ] && [ -x "$_rel" ]; then
        _candidates="$_rel"
    fi
    [ -n "$_path" ] && _candidates="$_candidates $_path"

    for _bin in $_candidates; do
        if "$_bin" internal "$_gate_subcommand" --help >/dev/null 2>&1; then
            printf '%s\n' "$_bin"
            return 0
        fi
    done
    return 1
}

__aida_gate_bin=$(__aida_resolve_gate_bin advisor-code-gate)
if [ -n "$__aida_gate_bin" ]; then
    if ! "$__aida_gate_bin" internal advisor-code-gate; then
        exit 1
    fi
elif command -v aida >/dev/null 2>&1; then
    # A stale/old aida is on PATH but no resolvable binary supports the gate
    # subcommand (version skew). Skip-with-a-warning rather than fail closed:
    # blocking a commit because the GATE BINARY is old just forces --no-verify,
    # which defeats this gate AND every check below it. trace:BUG-651
    printf 'pre-commit: advisor-code-gate skipped — no aida on PATH or in target/ supports it (stale/old build); not blocking the commit.\n' >&2
fi

# 2c. Automatic advisor-lock gate (STORY-711 slice 2). Same vendor-agnostic
# commit-boundary pattern as 2b, applied to the worktree lock: this worktree
# may carry an `authorized_by` lock (`aida lock acquire`); if the committing
# session's launch-context snapshot carries a DIFFERENT (or no) authorization
# token, `[locking] posture = "enforce"` refuses the commit (`"warn"` prints
# and proceeds; the default `"off"` is silent). Delegates to the binary
# (`aida internal locking-gate`) so the decision lives in ONE place shared
# with the `aida commit` CLI path. Same BUG-651 robust-resolution + fail-open
# behavior as the advisor-code-gate above. trace:TASK-1140
__aida_lock_gate_bin=$(__aida_resolve_gate_bin locking-gate)
if [ -n "$__aida_lock_gate_bin" ]; then
    if ! "$__aida_lock_gate_bin" internal locking-gate; then
        exit 1
    fi
elif command -v aida >/dev/null 2>&1; then
    printf 'pre-commit: locking-gate skipped — no aida on PATH or in target/ supports it (stale/old build); not blocking the commit.\n' >&2
fi

# 3. Auto-fmt staged Rust files before commit so cargo fmt --check (in CI)
# never catches drift after a local commit lands.
# Emergency skip: pass --no-verify to git commit.
# trace:TASK-503 | ai:antigravity
staged_rs=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)
if [ -n "$staged_rs" ]; then
    # Cheap check first
    if ! cargo fmt --all -- --check >/dev/null 2>&1; then
        echo 'pre-commit: cargo fmt --all detected drift, applying…'
        cargo fmt --all
        # Re-stage anything fmt touched
        echo "$staged_rs" | xargs git add
        echo 'pre-commit: drift fixed and re-staged'
    fi
fi

# 4. Get staged files (Added/Copied/Modified)
# Using git status --porcelain is completely safe and works on unborn branches (first commit)
STAGED_FILES=$(git status --porcelain 2>/dev/null | grep -E '^[AMRC]' | awk '{print $NF}')

IGNORED_STAGED_FILES=()
for file in $STAGED_FILES; do
    if git check-ignore --no-index -q "$file" 2>/dev/null; then
        IGNORED_STAGED_FILES+=("$file")
    fi
done

if [ ${#IGNORED_STAGED_FILES[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: ${IGNORED_STAGED_FILES[0]} is gitignored. Editing intermediate" >&2
    echo -e "build products produces non-reproducible fixes. Modify the" >&2
    echo -e "source (or pass --allow-intermediate to override). See:" >&2
    echo -e "docs/aida/discipline/substrate-as-bouncer.md${NC}" >&2
    
    if [ ${#IGNORED_STAGED_FILES[@]} -gt 1 ]; then
        echo -e "${RED}Other gitignored files staged:${NC}" >&2
        for ((i=1; i<${#IGNORED_STAGED_FILES[@]}; i++)); do
            echo -e "  - ${YELLOW}${IGNORED_STAGED_FILES[i]}${NC}" >&2
        done
    fi
    exit 1
fi

# 5. Substrate-as-bouncer: reject SPEC-ID *provenance* on `///` doc comments.
# A `///` doc comment on a clap field/variant doubles as `--help` text, so
# provenance on one leaks the developer breadcrumb into user-facing output
# (BUG-227 / TASK-268's "both-at-once trap"). The CI test
# source_doc_comments_carry_no_spec_id_provenance catches it minutes later; this
# gate catches it at the moment of writing.
#
# A line is *provenance* — and rejected — when it carries a `trace:` marker, OR
# is a *bare* SPEC-ID (essentially nothing but SPEC-ID token(s) + punctuation,
# no descriptive prose words). A *descriptive* mention of a SPEC-ID inside prose
# (e.g. `/// reuses the STORY-122 usage log`) is legitimate help text, NOT a
# leak, and is allowed (BUG-629 tightened this from the old over-broad "any
# SPEC-ID token" criterion, which forced agents to reword legit `///` prose).
# This is the SAME criterion as the cli.rs `doc_comment_is_provenance_leak`
# helper — keep the two in lockstep (TASK-903).
# Fix a real offender: demote the `///` to a plain `//` line above the item.
# Emergency skip: pass --no-verify (or --allow-intermediate, handled above).
#
# Scoped to the STAGED DIFF (added lines only), NOT whole staged files: a commit
# that merely TOUCHES a file carrying pre-existing `///` provenance debt must not
# be rejected for debt it didn't introduce — that just pushes agents to
# --no-verify, which ALSO skips the advisor-code-gate above, defeating both
# (BUG-624). We read `git diff --cached --unified=0` and inspect only `+`-added
# content lines (excluding the `+++ b/file` header), so only NEWLY-added `///`
# provenance blocks; pre-existing lines are ignored. Renames/binaries are
# diff-filtered out.
# trace:TASK-135 trace:BUG-624 trace:BUG-629 trace:TASK-903 | ai:claude
SPEC_ID_RE='(STORY|TASK|BUG|EPIC|SPIKE|FR|CR|SPEC|ADR|PRIN)-[0-9]+'

# Mirror of cli.rs `doc_comment_is_provenance_leak`. Input: a `///`-prefixed doc
# line. Returns 0 (leak → reject) when it carries `trace:` or is a bare SPEC-ID;
# returns 1 (allow) for a descriptive prose mention or no SPEC-ID at all.
__aida_doc_is_provenance_leak() {
    local docline="$1"
    # No SPEC-ID at all → nothing to leak.
    printf '%s\n' "$docline" | grep -qE "$SPEC_ID_RE" || return 1
    # A `trace:` marker on a `///` line is always provenance.
    case "$docline" in *trace:*) return 0 ;; esac
    # Strip the leading `///`, then delete every SPEC-ID token. If an alphabetic
    # word (2+ ascii letters) survives, this is descriptive prose → allow.
    # Otherwise only punctuation/digits remain → bare SPEC-ID → reject.
    local residual
    residual="$(printf '%s\n' "$docline" \
        | sed -E 's#^[[:space:]]*///+##; s/'"$SPEC_ID_RE"'/ /g')"
    if printf '%s\n' "$residual" | grep -qE '[A-Za-z]{2,}'; then
        return 1
    fi
    return 0
}

DOC_TRACE_OFFENDERS=()
current_file=""
while IFS= read -r line; do
    case "$line" in
        # New-side file header in the unified diff: remember which file the
        # following `+` lines belong to. Strip the "+++ b/" prefix (this branch
        # is tested BEFORE the generic "+"* arm so the header never counts as an
        # added content line).
        "+++ "*)
            current_file="${line#+++ }"
            current_file="${current_file#b/}"
            ;;
        # Any other line starting with "+" is added content. Strip the leading
        # "+" and apply the shared provenance criterion to the added line: a
        # `///` doc comment that is provenance (a `trace:` marker or a bare
        # SPEC-ID), but NOT a descriptive prose mention.
        "+"*)
            added="${line#+}"
            if printf '%s\n' "$added" | grep -qE '^[[:space:]]*///' \
                && __aida_doc_is_provenance_leak "$added"; then
                trimmed="${added#"${added%%[![:space:]]*}"}"
                DOC_TRACE_OFFENDERS+=("${current_file:-<staged>}: ${trimmed}")
            fi
            ;;
    esac
done < <(git diff --cached --unified=0 --no-color --diff-filter=ACMR -- '*.rs' 2>/dev/null || true)

if [ ${#DOC_TRACE_OFFENDERS[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: SPEC-ID provenance is on a \`///\` doc comment." >&2
    echo -e "clap pulls \`///\` doc blocks into \`--help\`, so a \`trace:\` marker or a" >&2
    echo -e "bare SPEC-ID leaks into user-facing output. Demote it to a plain \`//\`" >&2
    echo -e "comment above the item (a descriptive SPEC-ID mention in prose is fine)." >&2
    echo -e "See docs/user-facing-text-conventions.md${NC}" >&2
    echo -e "${YELLOW}Offending lines:${NC}" >&2
    for off in "${DOC_TRACE_OFFENDERS[@]}"; do
        echo -e "  - ${YELLOW}${off}${NC}" >&2
    done
    exit 1
fi

# 6. TASK-984: catch raw glyph LITERALS at commit time, not 7 min later at CI.
# Registry glyphs (status badges, work-routing markers, emoji) must route
# through aida-cli/src/glyphs.rs so the `[ui] glyphs = "ascii"` profile / the
# AIDA_GLYPHS env / a [glyphs] override apply; a raw literal typed inline
# silently bypasses all of that. scripts/glyph-lint.sh --block is the CI guard;
# running it HERE on just the staged aida-cli/src/*.rs files surfaces a new
# literal at the moment of writing instead of after a full CI cycle. Staged-
# files-scoped (and only when such files change) keeps it fast and stops it
# flagging pre-existing long-tail debt this commit didn't touch (BUG-624 spirit).
# Emergency skip: --no-verify. POSIX/dash-safe. trace:TASK-984
if [ -n "$__aida_repo_root" ] && [ -x "$__aida_repo_root/scripts/glyph-lint.sh" ]; then
    staged_glyph_files=$(git diff --cached --name-only --diff-filter=ACM -- aida-cli/src 2>/dev/null | grep '\.rs$' || true)
    if [ -n "$staged_glyph_files" ]; then
        # Word-split the newline list into per-file args (repo paths have no
        # spaces). glyph-lint.sh cd's to repo root, so relative paths resolve.
        if ! glyph_out=$("$__aida_repo_root/scripts/glyph-lint.sh" --block $staged_glyph_files 2>&1); then
            printf '%s\n' "$glyph_out" >&2
            printf 'pre-commit: raw glyph literal(s) in staged code — route them through aida-cli/src/glyphs.rs (Glyph::render). Caught locally to save a CI cycle. Emergency skip: --no-verify.\n' >&2
            exit 1
        fi
    fi
fi

# All gates passed: record the sentinel for the staged tree we just validated so
# the post-commit hook knows this commit's pre-commit ran (not --no-verify).
# trace:TASK-917
aida_precommit_sentinel
exit 0
