#!/bin/bash
# AIDA post-commit hook — direct --no-verify bypass detection (TASK-917).
# Generated by AIDA scaffolding.
#
# The pre-commit hook cannot observe its own bypass: `git commit --no-verify`
# means "don't run the pre-commit hook". So a --no-verify commit is caught only
# INDIRECTLY today — it surfaces later as CI red on whatever gate the pre-commit
# would have run. This hook is the DIRECT detector: the pre-commit hook writes
# the staged-tree SHA into a sentinel whenever it runs; here, after the commit
# lands, we compare that sentinel to the committed tree. Absent/stale sentinel
# ⇒ the pre-commit hook never ran for this commit ⇒ --no-verify was used.
#
# On a detected bypass it delegates to `aida internal record-no-verify-bypass`,
# which re-confirms and (only when the SPIKE-67 field study is enabled —
# AIDA_FIELD_STUDY=1) appends one `no-verify-bypass` event to the local
# ~/.aida/rule-violations.jsonl log. Observe-only: it never changes the commit
# (which already happened) and never fails. Falls open if `aida` isn't on PATH.
# trace:TASK-917

# Best-effort throughout — instrumentation must never disturb the workflow.
git_dir=$(git rev-parse --git-common-dir 2>/dev/null) || exit 0
case "$git_dir" in /*) ;; *) git_dir="$(pwd)/$git_dir" ;; esac
sentinel="$git_dir/aida-precommit-sentinel"

committed_tree=$(git rev-parse "HEAD^{tree}" 2>/dev/null) || exit 0
sentinel_tree=""
[ -f "$sentinel" ] && sentinel_tree=$(tr -d '[:space:]' < "$sentinel" 2>/dev/null)

# Consume the sentinel either way so it can't linger and mis-classify a later
# commit that happens to reuse the same tree.
rm -f "$sentinel" 2>/dev/null

# Sentinel matches the committed tree ⇒ the pre-commit hook ran ⇒ not a bypass.
[ -n "$sentinel_tree" ] && [ "$sentinel_tree" = "$committed_tree" ] && exit 0

# A bypass (or no pre-commit hook present): hand off to the binary, which
# re-confirms and records iff the field study is enabled. Never blocks.
if command -v aida >/dev/null 2>&1; then
    aida internal record-no-verify-bypass >/dev/null 2>&1 || true
fi

exit 0
