#!/bin/bash
# AIDA pre-commit hook - Substrate-as-bouncer gitignored file prevention
# Generated by AIDA scaffolding
# trace:FR-0226 | ai:claude:high

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# 0. --no-verify direct-detection sentinel (TASK-917).
# The pre-commit hook can't observe its own bypass: `git commit --no-verify`
# means "don't run this hook". So detection is INVERTED — this hook records the
# staged-tree SHA into a sentinel whenever it runs (including the legitimate
# early-exit allow paths below); the paired post-commit hook then compares the
# sentinel to the committed tree. A missing/stale sentinel ⇒ this hook never ran
# ⇒ --no-verify was used. `aida_precommit_sentinel` writes that marker; it is
# called before every `exit 0` so a clean allow is never mislabeled a bypass.
# trace:TASK-917
aida_precommit_sentinel() {
    local git_dir tree
    git_dir=$(git rev-parse --git-common-dir 2>/dev/null) || return 0
    case "$git_dir" in /*) ;; *) git_dir="$(pwd)/$git_dir" ;; esac
    tree=$(git write-tree 2>/dev/null) || return 0
    [ -n "$tree" ] && printf '%s\n' "$tree" > "$git_dir/aida-precommit-sentinel" 2>/dev/null
    return 0
}

# 1. Environment and argument bypass check
# Check if AIDA_ALLOW_INTERMEDIATE=1 is set, or if the git commit command was invoked with --allow-intermediate.
# We check /proc/$PPID/cmdline (Linux) for --allow-intermediate to enable seamless bypass.
if [ "$AIDA_ALLOW_INTERMEDIATE" = "1" ] || ( [ -f "/proc/$PPID/cmdline" ] && grep -q -z -- "--allow-intermediate" "/proc/$PPID/cmdline" 2>/dev/null ); then
    aida_precommit_sentinel  # this hook ran + allowed; not a --no-verify bypass. trace:TASK-917
    exit 0
fi

# 2. Special-case bypass for .aida-store worktree/branch (deliberate gitignored path commits)
CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
if [ "$CURRENT_BRANCH" = "aida-store" ] || [[ "$(pwd)" == *"/aida-store"* ]] || [[ "$(pwd)" == *"/.aida-store"* ]]; then
    # 2a. Store bulk-write version floor (trace:BUG-766). A stale installed
    # aida binary resolved from the raw PATH once ran unguarded bulk saves
    # that rewrote the whole object tree and dropped fields (the
    # deferred-shelf wipes). Guarded builds tag their git subprocesses with
    # AIDA_STORE_WRITE_GUARD; a commit staging MORE than the floor's worth
    # of objects/ files WITHOUT that marker can only come from a pre-guard
    # binary, so refuse it — an ancient binary may still read and make
    # small targeted writes, but never mass-rewrite the store. Floor is
    # tunable via AIDA_STORE_GUARD_FLOOR (0 disables the check).
    __aida_store_floor=${AIDA_STORE_GUARD_FLOOR:-10}
    if [ -z "$AIDA_STORE_WRITE_GUARD" ] && [ "$__aida_store_floor" -gt 0 ] 2>/dev/null; then
        __aida_store_staged=$(git diff --cached --name-only -- objects/ 2>/dev/null | wc -l | tr -d '[:space:]')
        if [ "$__aida_store_staged" -gt "$__aida_store_floor" ] 2>/dev/null; then
            echo "pre-commit: refusing bulk requirements-store write ($__aida_store_staged object files staged, floor $__aida_store_floor) from an aida binary without the store write guard — likely a stale installed build resolved from PATH." >&2
            echo "pre-commit: re-run with the current aida build, or set AIDA_STORE_GUARD_FLOOR=0 to bypass deliberately." >&2
            exit 1
        fi
    fi
    aida_precommit_sentinel  # trace:TASK-917
    exit 0
fi

# 2b. Advisor-no-code-write gate (STORY-684). VENDOR-AGNOSTIC substrate
# enforcement: this git pre-commit hook runs no matter which agent drove the
# commit (Claude, Codex, a raw terminal, a headless child), so the invariant
# "the advisor seat does specs/routing/review, NOT code" holds even where the
# Claude-only PreToolUse hook never fires. Delegates the decision to the binary
# (`aida internal advisor-code-gate`) so the rule lives in ONE place shared with
# the `aida commit` CLI path. Refuses (exit 1, aborting the commit) when an
# advisor session stages code with no sanctioned context; silent otherwise.
# Carve-outs (AIDA_AUTO_COMPLETE, solo mode, AIDA_ALLOW_ADVISOR_CODE=1) and the
# git-native --no-verify are the escape hatches. Falls open if `aida` isn't on
# PATH (this hook ships to repos that may not have the binary installed).
# trace:STORY-684
#
# BUG-651: resolve the gate binary ROBUSTLY. Agents commit in isolated worktrees
# where the `aida` on PATH is often a STALE released build (e.g. 0.9.1) that
# predates `internal advisor-code-gate`; that binary exits non-zero on an
# unknown-subcommand error, which used to ABORT the commit even with no real
# violation — pushing agents to --no-verify (which also skips every check
# below). Fix: (a) prefer a freshest in-repo target/{debug,release}/aida (which
# tracks the working source) over a possibly-stale PATH aida; and (b) if NO
# resolvable binary actually supports the subcommand (version skew), skip with a
# warning instead of failing closed. The gate runs when it CAN; it never blocks
# a commit because the binary is old. POSIX/dash-safe (no bashisms in this
# block). trace:BUG-651
__aida_repo_root=$(git rev-parse --show-toplevel 2>/dev/null)

# Probe whether a binary supports a given `internal <subcommand>` WITHOUT side
# effects: `... --help` exits 0 when the subcommand exists, non-zero (clap
# error) on a stale binary that never had it. Echoes the first supporting
# binary, preferring the freshest in-repo build, then the PATH `aida`.
# Generalized (TASK-1140) from the advisor-code-gate-only original so the
# locking gate below can reuse the same robust resolution instead of a second
# copy. trace:BUG-651 trace:TASK-1140
__aida_resolve_gate_bin() {
    _gate_subcommand="$1"
    _dbg="$__aida_repo_root/target/debug/aida"
    _rel="$__aida_repo_root/target/release/aida"
    _path=$(command -v aida 2>/dev/null)

    _candidates=""
    if [ -n "$__aida_repo_root" ] && [ -x "$_dbg" ] && [ -x "$_rel" ]; then
        if [ "$_dbg" -nt "$_rel" ]; then
            _candidates="$_dbg $_rel"
        else
            _candidates="$_rel $_dbg"
        fi
    elif [ -n "$__aida_repo_root" ] && [ -x "$_dbg" ]; then
        _candidates="$_dbg"
    elif [ -n "$__aida_repo_root" ] && [ -x "$_rel" ]; then
        _candidates="$_rel"
    fi
    [ -n "$_path" ] && _candidates="$_candidates $_path"

    for _bin in $_candidates; do
        if "$_bin" internal "$_gate_subcommand" --help >/dev/null 2>&1; then
            printf '%s\n' "$_bin"
            return 0
        fi
    done
    return 1
}

__aida_gate_bin=$(__aida_resolve_gate_bin advisor-code-gate)
if [ -n "$__aida_gate_bin" ]; then
    if ! "$__aida_gate_bin" internal advisor-code-gate; then
        exit 1
    fi
elif command -v aida >/dev/null 2>&1; then
    # A stale/old aida is on PATH but no resolvable binary supports the gate
    # subcommand (version skew). Skip-with-a-warning rather than fail closed:
    # blocking a commit because the GATE BINARY is old just forces --no-verify,
    # which defeats this gate AND every check below it. trace:BUG-651
    printf 'pre-commit: advisor-code-gate skipped — no aida on PATH or in target/ supports it (stale/old build); not blocking the commit.\n' >&2
fi

# 2c. Automatic advisor-lock gate (STORY-711 slice 2). Same vendor-agnostic
# commit-boundary pattern as 2b, applied to the worktree lock: this worktree
# may carry an `authorized_by` lock (`aida lock acquire`); if the committing
# session's launch-context snapshot carries a DIFFERENT (or no) authorization
# token, `[locking] posture = "enforce"` refuses the commit (`"warn"` prints
# and proceeds; the default `"off"` is silent). Delegates to the binary
# (`aida internal locking-gate`) so the decision lives in ONE place shared
# with the `aida commit` CLI path. Same BUG-651 robust-resolution + fail-open
# behavior as the advisor-code-gate above. trace:TASK-1140
__aida_lock_gate_bin=$(__aida_resolve_gate_bin locking-gate)
if [ -n "$__aida_lock_gate_bin" ]; then
    if ! "$__aida_lock_gate_bin" internal locking-gate; then
        exit 1
    fi
elif command -v aida >/dev/null 2>&1; then
    printf 'pre-commit: locking-gate skipped — no aida on PATH or in target/ supports it (stale/old build); not blocking the commit.\n' >&2
fi

# 2d. Worktree-scope guard (TASK-1178) — DETECT, do not prevent. An agent in a
# worktree-scoped session can still write into the SHARED main checkout (stale
# cwd, an absolute path from an earlier session, a tool run from the wrong
# directory). AIDA cannot stop the write — that is a harness/filesystem concern
# — but the commit boundary is where the mistake becomes visible, so this gate
# WARNS, naming the staged paths that resolve outside the session worktree.
# Unlike 2b/2c this is warn-only: the binary always exits 0, and the `|| true`
# below makes that structural, so a scope warning can never abort a commit (a
# hard block here would just push agents to --no-verify, which also skips every
# gate above). Silent for an in-worktree commit and for any session that is not
# worktree-scoped. Same BUG-651 robust binary resolution; no "skipped" notice on
# an old binary — an advisory check should not add noise when it cannot run.
# trace:TASK-1178
__aida_scope_gate_bin=$(__aida_resolve_gate_bin worktree-scope-gate)
if [ -n "$__aida_scope_gate_bin" ]; then
    "$__aida_scope_gate_bin" internal worktree-scope-gate || true
fi

# 3. Auto-fmt staged Rust files before commit so cargo fmt --check (in CI)
# never catches drift after a local commit lands.
# Emergency skip: pass --no-verify to git commit.
# trace:TASK-503 | ai:antigravity
#
# BUG-1661: a failing `cargo fmt --check` is not always drift. When cargo itself
# cannot run (no rustup default toolchain, no rustfmt component, no Cargo.toml
# in this repo) the check exits non-zero too, and the old step then ran
# `cargo fmt --all` (which failed the same way) and still printed "drift fixed
# and re-staged". Report the failure honestly instead: claim a fix only when
# `cargo fmt --all` exits 0, and say what went wrong otherwise. The commit still
# proceeds either way — this step is a convenience, CI's `cargo fmt --check` is
# the gate — so a broken toolchain never pushes an agent to --no-verify.
# trace:BUG-1661 | ai:claude
staged_rs=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)
if [ -n "$staged_rs" ]; then
    if ! command -v cargo >/dev/null 2>&1; then
        printf 'pre-commit: cargo not on PATH; skipping the rustfmt step (CI runs cargo fmt --check).\n' >&2
    # Cheap check first
    elif ! __aida_fmt_check_err=$(cargo fmt --all -- --check 2>&1 >/dev/null); then
        echo 'pre-commit: cargo fmt --all --check did not pass, applying…'
        if __aida_fmt_err=$(cargo fmt --all 2>&1 >/dev/null); then
            # Re-stage anything fmt touched
            echo "$staged_rs" | xargs git add
            echo 'pre-commit: drift fixed and re-staged'
        else
            __aida_fmt_reason=$(printf '%s\n' "${__aida_fmt_err:-$__aida_fmt_check_err}" | grep -v '^[[:space:]]*$' | head -n 1)
            printf 'pre-commit: cargo fmt --all FAILED; staged Rust files were NOT reformatted or re-staged.\n' >&2
            [ -n "$__aida_fmt_reason" ] && printf 'pre-commit:   %s\n' "$__aida_fmt_reason" >&2
            printf 'pre-commit:   fix the toolchain (rustup default / rustfmt component) or run cargo fmt --all by hand; CI checks formatting.\n' >&2
        fi
    fi
fi

# 4. Get staged files (Added/Copied/Modified)
# Using git status --porcelain is completely safe and works on unborn branches (first commit)
STAGED_FILES=$(git status --porcelain 2>/dev/null | grep -E '^[AMRC]' | awk '{print $NF}')

IGNORED_STAGED_FILES=()
for file in $STAGED_FILES; do
    # Tracked, edited source files can match deny-by-default ignore patterns
    # (for example template masters under aida-core/templates/.aida/). Only
    # newly added ignored paths are intermediate artifacts. trace:BUG-1088 | ai:codex
    if git ls-files --error-unmatch -- "$file" >/dev/null 2>&1 \
        && git diff --cached --quiet --diff-filter=A -- "$file" 2>/dev/null; then
        continue
    fi

    if git check-ignore --no-index -q "$file" 2>/dev/null; then
        IGNORED_STAGED_FILES+=("$file")
    fi
done

if [ ${#IGNORED_STAGED_FILES[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: ${IGNORED_STAGED_FILES[0]} is gitignored. Editing intermediate" >&2
    echo -e "build products produces non-reproducible fixes. Modify the" >&2
    echo -e "source (or pass --allow-intermediate to override). See:" >&2
    echo -e ".aida/discipline/substrate-as-bouncer.md${NC}" >&2
    
    if [ ${#IGNORED_STAGED_FILES[@]} -gt 1 ]; then
        echo -e "${RED}Other gitignored files staged:${NC}" >&2
        for ((i=1; i<${#IGNORED_STAGED_FILES[@]}; i++)); do
            echo -e "  - ${YELLOW}${IGNORED_STAGED_FILES[i]}${NC}" >&2
        done
    fi
    exit 1
fi

# 5. Substrate-as-bouncer: reject SPEC-ID *provenance* on `///` doc comments.
# A `///` doc comment on a clap field/variant doubles as `--help` text, so
# provenance on one leaks the developer breadcrumb into user-facing output
# (BUG-227 / TASK-268's "both-at-once trap"). The CI test
# source_doc_comments_carry_no_spec_id_provenance catches it minutes later; this
# gate catches it at the moment of writing.
#
# A line is *provenance* — and rejected — when it carries a `trace:` marker, OR
# is a *bare* SPEC-ID (essentially nothing but SPEC-ID token(s) + punctuation,
# no descriptive prose words). A *descriptive* mention of a SPEC-ID inside prose
# (e.g. `/// reuses the STORY-122 usage log`) is legitimate help text, NOT a
# leak, and is allowed (BUG-629 tightened this from the old over-broad "any
# SPEC-ID token" criterion, which forced agents to reword legit `///` prose).
# This hook ships to every scaffolded project and scans every staged `*.rs`
# file, where ordinary rustdoc legitimately cites a project's own ids (`/// See
# ADR-12 for the rationale`), so it deliberately keeps this narrower criterion.
# AIDA's own stricter "no SPEC-ID in `--help` prose at all" rule lives ONLY in
# the cli.rs CI guard (`doc_comment_is_provenance_leak`), which scans just the
# clap source (TASK-1516). The two share the SAME id pattern (prefixes and
# leading word boundary) — keep `SPEC_ID_RE` here and the cli.rs regex in
# lockstep (TASK-903).
# Fix a real offender: demote the `///` to a plain `//` line above the item.
# Emergency skip: pass --no-verify (or --allow-intermediate, handled above).
#
# Scoped to the STAGED DIFF (added lines only), NOT whole staged files: a commit
# that merely TOUCHES a file carrying pre-existing `///` provenance debt must not
# be rejected for debt it didn't introduce — that just pushes agents to
# --no-verify, which ALSO skips the advisor-code-gate above, defeating both
# (BUG-624). We read `git diff --cached --unified=0` and inspect only `+`-added
# content lines (excluding the `+++ b/file` header), so only NEWLY-added `///`
# provenance blocks; pre-existing lines are ignored. Renames/binaries are
# diff-filtered out.
#
# MOVED lines are not NEW debt (TASK-144): a mechanical file-split/move re-adds
# pre-existing `///` provenance verbatim (deleted from the source file in the
# SAME staged diff), and the added-lines-only heuristic used to refuse the
# commit for debt it merely relocated (~85 false-flagged lines during the
# STORY-771 extraction). So we first collect the `-`-removed `///` provenance
# lines from the staged diff (whitespace-trimmed, counted) and each added
# offender candidate that matches a removed line CONSUMES one removal credit
# and is excused. Genuinely new `///` provenance (no matching staged removal)
# is still refused, including extra copies beyond the number removed. The
# removal pass diff-filters D too, so a move whose source file is deleted
# outright still credits its lines.
#
# `SPEC_ID_RE` carries an explicit leading word boundary `(^|[^A-Za-z0-9_])`
# (POSIX ERE has no portable `\b`), so an id-shaped substring of a longer word
# (`DEBUG-2` → `BUG-2`, `SCR-4` → `CR-4`) is not mistaken for a SPEC-ID. The
# cli.rs guard uses this exact pattern string — change both together.
# trace:TASK-135 trace:BUG-624 trace:BUG-629 trace:TASK-903 trace:TASK-144 trace:TASK-1516 | ai:claude
SPEC_ID_RE='(^|[^A-Za-z0-9_])(STORY|TASK|BUG|EPIC|SPIKE|FR|CR|SPEC|ADR|PRIN|DOC)-[0-9]+'

# A rustdoc line is EXACTLY three slashes (`///`), optionally indented. Four or
# more (`////`) is a plain comment to rustc — never rendered into `--help` — so
# provenance on it is fine and must not be refused (BUG-1661). The `([^/]|$)`
# tail rejects the longer runs; `$` keeps a bare `///` line matching.
# trace:BUG-1661 | ai:claude
DOC_COMMENT_RE='^[[:space:]]*///([^/]|$)'

# Both passes below run as ONE POSIX-awk program over the staged diff (BUG-1925).
# The old shell loop spawned `printf | grep` for every `+`/`-` diff line and
# scanned the removal-credit array linearly for every added candidate, so a
# 250k-line move (the TASK-1538 lib.rs split) held the hook for 20+ minutes. In
# awk the doc-comment test is an in-process regex, and removal credits are a
# hash of trimmed line -> count, so each move credit is O(1). Only the BSD/macOS
# baseline is used: POSIX awk (no gawk extensions), bash 3.2 (no `declare -A`,
# no `mapfile`). trace:BUG-1925 | ai:claude
#
# `__aida_doc_is_provenance_leak` is the bare-ID / `trace:` provenance check
# (the cli.rs CI guard is intentionally stricter — see above; only the id
# pattern is shared). Input: a `///`-prefixed doc line. Returns 1 (leak →
# reject) when it carries `trace:` or is a bare SPEC-ID; 0 (allow) for a
# descriptive prose mention or no SPEC-ID at all. It strips the leading `///`,
# deletes every SPEC-ID token (plus the single boundary char before it), and
# allows the line if an alphabetic word (2+ ascii letters) survives.
#
# Move matching (TASK-144) is per diff: every `-`-removed `///` provenance line,
# trimmed of BOTH leading and trailing whitespace (indentation often changes
# when a line moves, e.g. into an impl block, and that does not make relocated
# debt new), adds one credit. Each added candidate, in diff order, consumes one
# credit for its trimmed text and is excused; with no credit left it is NEW
# debt and refused, including extra copies beyond the number removed. Credits
# are settled at the end of each diff, so a removal later in the diff still
# credits an earlier addition, exactly as the old two-pass loop did.
#
# MERGE COMMITS (BUG-1925): `git diff --cached` compares the index with the
# first parent only, so merging main into a branch re-checked every line main
# brought in, content that already passed this hook on main. With MERGE_HEAD
# present the staged tree is diffed against EVERY parent, and an offender is
# reported only as many times as it appears in all of those diffs: a line taken
# verbatim from either side is absent from that side's diff, so only lines that
# differ from every parent (the conflict resolution) are checked.
#
# Progress: the scan reports on stderr every 100000 diff lines, and the shell
# reports the total when it took 3 s or more, so an agent can tell a slow hook
# from a hung one. trace:BUG-1925 | ai:claude
__aida_prov_parents=""
if git rev-parse -q --verify MERGE_HEAD >/dev/null 2>&1 \
    && git rev-parse -q --verify HEAD >/dev/null 2>&1; then
    __aida_merge_head_file=$(git rev-parse --git-path MERGE_HEAD 2>/dev/null)
    __aida_prov_parents="HEAD"
    if [ -n "$__aida_merge_head_file" ] && [ -f "$__aida_merge_head_file" ]; then
        while IFS= read -r __aida_parent || [ -n "$__aida_parent" ]; do
            case "$__aida_parent" in
                ''|*[!0-9a-fA-F]*) ;;
                *) __aida_prov_parents="$__aida_prov_parents $__aida_parent" ;;
            esac
        done < "$__aida_merge_head_file"
    fi
    if [ "$__aida_prov_parents" = "HEAD" ]; then
        __aida_prov_parents=""
    else
        printf 'pre-commit: merge commit; checking /// provenance only on lines that differ from every parent (the conflict resolution).\n' >&2
    fi
fi

# Emit the staged `*.rs` diff(s), each introduced by a `#AIDA-DIFF` boundary
# line (no unified-diff line starts with `#`). `D` is included so lines removed
# by deleting a whole source file still register as move credits; deleted files
# contribute no `+` lines, so the added-lines side is unaffected.
# trace:TASK-144 trace:BUG-1925 | ai:claude
__aida_staged_rs_diffs() {
    local parent
    if [ -z "$__aida_prov_parents" ]; then
        printf '#AIDA-DIFF index\n'
        git diff --cached --unified=0 --no-color --diff-filter=ACDMR -- '*.rs' 2>/dev/null
        return 0
    fi
    for parent in $__aida_prov_parents; do
        printf '#AIDA-DIFF %s\n' "$parent"
        git diff --cached --unified=0 --no-color --diff-filter=ACDMR "$parent" -- '*.rs' 2>/dev/null
    done
    return 0
}

__aida_prov_started=$SECONDS
__aida_prov_offenders=$(__aida_staged_rs_diffs | awk -v spec_re="$SPEC_ID_RE" -v doc_re="$DOC_COMMENT_RE" '
function __aida_doc_is_provenance_leak(doc,    residual) {
    if (doc !~ spec_re) return 0
    if (index(doc, "trace:") > 0) return 1
    residual = doc
    sub(/^[[:space:]]*\/\/\/+/, "", residual)
    gsub(spec_re, " ", residual)
    if (residual ~ /[A-Za-z][A-Za-z]/) return 0
    return 1
}
function trim_ws(s) {
    sub(/^[[:space:]]+/, "", s)
    sub(/[[:space:]]+$/, "", s)
    return s
}
# Settle one diff: spend move credits on its candidates in diff order, then
# fold the surviving offenders into the cross-parent intersection.
function settle(    i, key, off) {
    if (ndiff == 0) return
    split("", seen_now)
    for (i = 1; i <= ncand; i++) {
        key = cand_key[i]
        if (credit[key] > 0) { credit[key]--; continue }
        off = cand_off[i]
        if (ndiff == 1) {
            nfirst++
            first_off[nfirst] = off
            allowed[off]++
        } else {
            seen_now[off]++
        }
    }
    if (ndiff > 1) {
        for (off in allowed) {
            if (seen_now[off] + 0 < allowed[off]) allowed[off] = seen_now[off] + 0
        }
    }
    split("", credit)
    split("", cand_key)
    split("", cand_off)
    ncand = 0
}
/^#AIDA-DIFF / { settle(); ndiff++; current_file = ""; next }
{
    lines++
    if (lines % 100000 == 0) {
        printf "pre-commit: /// provenance scan: %d staged diff lines checked...\n", lines | "cat 1>&2"
    }
}
# Old-side file header ("--- a/file") is not removed content: match it BEFORE
# the generic "-" rule.
/^--- / { next }
/^-/ {
    text = substr($0, 2)
    if (text ~ doc_re && __aida_doc_is_provenance_leak(text)) credit[trim_ws(text)]++
    next
}
# New-side file header: remember which file the following "+" lines belong to.
/^\+\+\+ / {
    current_file = substr($0, 5)
    if (substr(current_file, 1, 2) == "b/") current_file = substr(current_file, 3)
    next
}
/^\+/ {
    text = substr($0, 2)
    if (text ~ doc_re && __aida_doc_is_provenance_leak(text)) {
        ncand++
        cand_key[ncand] = trim_ws(text)
        lead = text
        sub(/^[[:space:]]+/, "", lead)
        cand_off[ncand] = (current_file == "" ? "<staged>" : current_file) ": " lead
    }
    next
}
END {
    settle()
    for (i = 1; i <= nfirst; i++) {
        off = first_off[i]
        if (emitted[off] + 0 < allowed[off]) {
            emitted[off]++
            print off
        }
    }
}')
__aida_prov_elapsed=$((SECONDS - __aida_prov_started))
if [ "$__aida_prov_elapsed" -ge 3 ]; then
    printf 'pre-commit: /// provenance scan took %ss.\n' "$__aida_prov_elapsed" >&2
fi

DOC_TRACE_OFFENDERS=()
if [ -n "$__aida_prov_offenders" ]; then
    while IFS= read -r off; do
        DOC_TRACE_OFFENDERS+=("$off")
    done <<< "$__aida_prov_offenders"
fi

if [ ${#DOC_TRACE_OFFENDERS[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: SPEC-ID provenance is on a \`///\` doc comment." >&2
    echo -e "clap pulls \`///\` doc blocks into \`--help\`, so a \`trace:\` marker or a" >&2
    echo -e "bare SPEC-ID leaks into user-facing output. Demote it to a plain \`//\`" >&2
    echo -e "comment above the item (a descriptive SPEC-ID mention in prose is fine)." >&2
    echo -e "See docs/user-facing-text-conventions.md${NC}" >&2
    echo -e "${YELLOW}Offending lines:${NC}" >&2
    for off in "${DOC_TRACE_OFFENDERS[@]}"; do
        echo -e "  - ${YELLOW}${off}${NC}" >&2
    done
    exit 1
fi

# 6. TASK-984: catch raw glyph LITERALS at commit time, not 7 min later at CI.
# Registry glyphs (status badges, work-routing markers, emoji) must route
# through aida-cli/src/glyphs.rs so the `[ui] glyphs = "ascii"` profile / the
# AIDA_GLYPHS env / a [glyphs] override apply; a raw literal typed inline
# silently bypasses all of that. scripts/glyph-lint.sh --block is the CI guard;
# running it HERE on just the staged aida-cli/src/*.rs files surfaces a new
# literal at the moment of writing instead of after a full CI cycle. Staged-
# files-scoped (and only when such files change) keeps it fast and stops it
# flagging pre-existing long-tail debt this commit didn't touch (BUG-624 spirit).
# Emergency skip: --no-verify. POSIX/dash-safe. trace:TASK-984
if [ -n "$__aida_repo_root" ] && [ -x "$__aida_repo_root/scripts/glyph-lint.sh" ]; then
    staged_glyph_files=$(git diff --cached --name-only --diff-filter=ACM -- aida-cli/src 2>/dev/null | grep '\.rs$' || true)
    if [ -n "$staged_glyph_files" ]; then
        # Word-split the newline list into per-file args (repo paths have no
        # spaces). glyph-lint.sh cd's to repo root, so relative paths resolve.
        if ! glyph_out=$("$__aida_repo_root/scripts/glyph-lint.sh" --block $staged_glyph_files 2>&1); then
            printf '%s\n' "$glyph_out" >&2
            printf 'pre-commit: raw glyph literal(s) in staged code — route them through aida-cli/src/glyphs.rs (Glyph::render). Caught locally to save a CI cycle. Emergency skip: --no-verify.\n' >&2
            exit 1
        fi
    fi
fi

# All gates passed: record the sentinel for the staged tree we just validated so
# the post-commit hook knows this commit's pre-commit ran (not --no-verify).
# trace:TASK-917
aida_precommit_sentinel
exit 0
