#!/bin/bash
# AIDA pre-commit hook - Substrate-as-bouncer gitignored file prevention
# Generated by AIDA scaffolding
# trace:FR-0226 | ai:claude:high

# Colors for output
RED='\033[0;31m'
YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# 1. Environment and argument bypass check
# Check if AIDA_ALLOW_INTERMEDIATE=1 is set, or if the git commit command was invoked with --allow-intermediate.
# We check /proc/$PPID/cmdline (Linux) for --allow-intermediate to enable seamless bypass.
if [ "$AIDA_ALLOW_INTERMEDIATE" = "1" ] || ( [ -f "/proc/$PPID/cmdline" ] && grep -q -z -- "--allow-intermediate" "/proc/$PPID/cmdline" 2>/dev/null ); then
    exit 0
fi

# 2. Special-case bypass for .aida-store worktree/branch (deliberate gitignored path commits)
CURRENT_BRANCH=$(git symbolic-ref --short HEAD 2>/dev/null)
if [ "$CURRENT_BRANCH" = "aida-store" ] || [[ "$(pwd)" == *"/aida-store"* ]] || [[ "$(pwd)" == *"/.aida-store"* ]]; then
    exit 0
fi

# 3. Auto-fmt staged Rust files before commit so cargo fmt --check (in CI)
# never catches drift after a local commit lands.
# Emergency skip: pass --no-verify to git commit.
# trace:TASK-503 | ai:antigravity
staged_rs=$(git diff --cached --name-only --diff-filter=ACM | grep '\.rs$' || true)
if [ -n "$staged_rs" ]; then
    # Cheap check first
    if ! cargo fmt --all -- --check >/dev/null 2>&1; then
        echo 'pre-commit: cargo fmt --all detected drift, applying…'
        cargo fmt --all
        # Re-stage anything fmt touched
        echo "$staged_rs" | xargs git add
        echo 'pre-commit: drift fixed and re-staged'
    fi
fi

# 4. Get staged files (Added/Copied/Modified)
# Using git status --porcelain is completely safe and works on unborn branches (first commit)
STAGED_FILES=$(git status --porcelain 2>/dev/null | grep -E '^[AMRC]' | awk '{print $NF}')

IGNORED_STAGED_FILES=()
for file in $STAGED_FILES; do
    if git check-ignore --no-index -q "$file" 2>/dev/null; then
        IGNORED_STAGED_FILES+=("$file")
    fi
done

if [ ${#IGNORED_STAGED_FILES[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: ${IGNORED_STAGED_FILES[0]} is gitignored. Editing intermediate" >&2
    echo -e "build products produces non-reproducible fixes. Modify the" >&2
    echo -e "source (or pass --allow-intermediate to override). See:" >&2
    echo -e "docs/aida/discipline/substrate-as-bouncer.md${NC}" >&2
    
    if [ ${#IGNORED_STAGED_FILES[@]} -gt 1 ]; then
        echo -e "${RED}Other gitignored files staged:${NC}" >&2
        for ((i=1; i<${#IGNORED_STAGED_FILES[@]}; i++)); do
            echo -e "  - ${YELLOW}${IGNORED_STAGED_FILES[i]}${NC}" >&2
        done
    fi
    exit 1
fi

# 5. Substrate-as-bouncer: reject SPEC-ID trace markers on `///` doc comments.
# A `///` doc comment on a clap field/variant doubles as `--help` text, so a
# `trace:` marker on one leaks the developer breadcrumb into user-facing output
# (BUG-227 / TASK-268's "both-at-once trap"). The CI tests
# source_doc_comments_carry_no_trace_token + help_text_carries_no_trace_markers
# catch it minutes later in CI; this gate catches it at the moment of writing.
# Fix: demote the offending `///` to a plain `//` line above the item.
# Emergency skip: pass --no-verify (or --allow-intermediate, handled above).
# trace:TASK-135 | ai:claude
DOC_TRACE_OFFENDERS=()
for file in $staged_rs; do
    # Read the staged blob (not the worktree) so partial staging is honored
    # and any fmt re-staging above is reflected.
    while IFS= read -r match; do
        [ -n "$match" ] && DOC_TRACE_OFFENDERS+=("$file:$match")
    done < <(git show ":$file" 2>/dev/null | grep -nE '^[[:space:]]*///.*trace:' || true)
done

if [ ${#DOC_TRACE_OFFENDERS[@]} -gt 0 ]; then
    echo -e "${RED}Refusing commit: a SPEC-ID trace marker is on a \`///\` doc comment." >&2
    echo -e "clap pulls \`///\` doc blocks into \`--help\`, so the marker leaks into" >&2
    echo -e "user-facing output. Demote it to a plain \`//\` comment above the item" >&2
    echo -e "(SPEC-IDs stay in code as \`//\`, never \`///\`). See:" >&2
    echo -e "docs/user-facing-text-conventions.md${NC}" >&2
    echo -e "${YELLOW}Offending lines:${NC}" >&2
    for off in "${DOC_TRACE_OFFENDERS[@]}"; do
        echo -e "  - ${YELLOW}${off}${NC}" >&2
    done
    exit 1
fi

exit 0
