// This file was generated by `aida-generate-types`.

// Do not edit this file manually.

// It is used to keep Rust and TypeScript types in sync.

export type RequirementStatus = "Draft" | "Approved" | "Planned" | "InProgress" | "Done" | "Completed" | "Rejected" | "NeedsAttention";

export type PuntCategory = "design-fork" | "ambiguous-spec" | "missing-context" | "blocked-dependency" | "other";

export type AttentionReason = { 
/**
 * The kind of obstacle that triggered the punt.
 */
category: PuntCategory, 
/**
 * Human-readable description of the fork / obstacle the agent hit.
 */
detail: string, 
/**
 * The raiser's best-guess answer if forced to pick — distinct from
 * `detail` so the fork and the lean stay separable. `None` when the
 * agent had no defensible lean.
 */
lean?: string | null, 
/**
 * Role / agent that raised the punt (the active session role, or
 * `None` when no role context was available).
 */
raised_by?: string | null, 
/**
 * When the punt was raised.
 */
raised_at: string, };

export type FailureReason = { 
/**
 * Stable slug for the phase that failed — `implementer`, `ci`,
 * `review`, `merge`, `pull`, or `build`. A string (not an enum)
 * keeps `aida-core` free of orchestrator concepts: the source of
 * truth for phase identities lives in `aida-cli::auto_complete`.
 */
phase: string, 
/**
 * 1-based phase index (1..=6) for sorting / display.
 */
phase_index: number, 
/**
 * Stable slug for the failure kind — `no-pr`, `ci-red`,
 * `request-changes`, `merge-conflict`, etc. Mirrors the orchestrator's
 * existing `PhaseFailureKind::slug()`.
 */
kind: string, 
/**
 * One-line human description of what went wrong.
 */
detail: string, 
/**
 * Pre-rendered recovery hint — what the orchestrator would tell a
 * human standing in front of the broken phase. Cached here so
 * triage doesn't have to rebuild it.
 */
recovery_hint?: string | null, 
/**
 * Role / agent that shelved the spec (the active session role,
 * `None` when no role context was available).
 */
shelved_by?: string | null, 
/**
 * When the spec was shelved.
 */
shelved_at: string, };

export type DecisionChoice = { 
/**
 * Short human label for the option (what the human picks).
 */
label: string, 
/**
 * What happens / what this option means, in human terms.
 */
consequence: string, 
/**
 * Deterministic action token the loop will eventually apply (NOT
 * applied in slice 1). Never free-form prose — a parseable token.
 */
resolution: string, };

export type DecisionRequest = { 
/**
 * The self-contained question (state / deciding factor distilled so the
 * human needs no spec re-read to answer).
 */
question: string, 
/**
 * Enumerated, actionable choices (≥2). Each maps to a resolution token.
 */
choices: Array<DecisionChoice>, 
/**
 * 0-based index of the recommended default choice, if any.
 */
recommended?: number | null, 
/**
 * Why the recommended default is recommended (the advisor's reasoning).
 */
rationale?: string | null, 
/**
 * 0-based index of the chosen answer. `None` while the request is
 * pending (unanswered).
 */
answered?: number | null, 
/**
 * When the question was first posed.
 */
asked_at?: string | null, 
/**
 * When the human answered it.
 */
answered_at?: string | null, };

export type RequirementPriority = "High" | "Medium" | "Low";

export type RequirementType = "Functional" | "NonFunctional" | "System" | "User" | "ChangeRequest" | "Bug" | "Epic" | "Story" | "Task" | "Spike" | "Sprint" | "Folder" | "Meta" | "Principle" | "Vision" | "Constraint" | "Decision" | "Term" | "Doc";

export type MetaSubtype = "Prompt" | "Skill" | "Command" | "Template" | "Config";

export type RelationshipType = "Parent" | "Child" | "Duplicate" | "Verifies" | "VerifiedBy" | "References" | "BlockedBy" | "Blocks" | { "Custom": string };

export type CustomFieldType = "text" | "textarea" | "select" | "boolean" | "date" | "user" | "requirement" | "number";

export type CustomFieldDefinition = { 
/**
 * Field name (used as key in custom_fields map)
 */
name: string, 
/**
 * Display label for the field
 */
label: string, 
/**
 * Field type
 */
field_type: CustomFieldType, 
/**
 * Whether this field is required
 */
required: boolean, 
/**
 * Options for Select field type
 */
options?: Array<string>, 
/**
 * Default value (as string, converted based on field_type)
 */
default_value: string | null, 
/**
 * Help text / description
 */
description: string | null, 
/**
 * Display order (lower = first)
 */
order: number, };

export type CustomTypeDefinition = { 
/**
 * Internal name/key for the type (e.g., "ChangeRequest")
 */
name: string, 
/**
 * Display label (e.g., "Change Request")
 */
display_name: string, 
/**
 * Description of this type
 */
description: string | null, 
/**
 * Preferred ID prefix for this type (e.g., "CR")
 */
prefix: string | null, 
/**
 * Custom statuses for this type (if empty, uses default statuses)
 */
statuses?: Array<string>, 
/**
 * Custom priorities for this type (if empty, uses default priorities)
 */
priorities?: Array<string>, 
/**
 * Additional custom fields for this type
 */
custom_fields?: Array<CustomFieldDefinition>, 
/**
 * Whether this is a built-in type (cannot be deleted)
 */
built_in: boolean, 
/**
 * Color for visual distinction (hex color code)
 */
color: string | null, 
/**
 * Whether this type is stateless (no status/priority tracking)
 * Stateless types are used for organizational purposes (e.g., Folders)
 * They are excluded from status metrics and reports by default
 */
stateless: boolean, };

export type Cardinality = "OneToOne" | "OneToMany" | "ManyToOne" | "ManyToMany";

export type RelationshipDefinition = { 
/**
 * Unique identifier for this relationship type (lowercase, no spaces)
 */
name: string, 
/**
 * Human-readable display name
 */
display_name: string, 
/**
 * Description of what this relationship means
 */
description: string, 
/**
 * The inverse relationship name (if any)
 * e.g., "parent" has inverse "child"
 */
inverse: string | null, 
/**
 * Whether this relationship is symmetric (A->B implies B->A with same type)
 * e.g., "duplicate" is symmetric
 */
symmetric: boolean, 
/**
 * Cardinality constraints
 */
cardinality: Cardinality, 
/**
 * Source type constraints (which requirement types can be the source)
 * Empty means all types allowed
 */
source_types: Array<string>, 
/**
 * Target type constraints (which requirement types can be the target)
 * Empty means all types allowed
 */
target_types: Array<string>, 
/**
 * Whether this is a built-in relationship (cannot be deleted)
 */
built_in: boolean, 
/**
 * Color for visualization (optional, hex format e.g., "#ff6b6b")
 */
color: string | null, 
/**
 * Icon/symbol for the relationship (optional)
 */
icon: string | null, };

export type IdFormat = "SingleLevel" | "TwoLevel";

export type NumberingStrategy = "Global" | "PerPrefix" | "PerFeatureType";

export type RequirementTypeDefinition = { 
/**
 * Display name for the type (e.g., "Functional")
 */
name: string, 
/**
 * Prefix used in IDs (e.g., "FR")
 */
prefix: string, 
/**
 * Optional description
 */
description: string, };

export type FeatureDefinition = { 
/**
 * Sequential number for ordering
 */
number: number, 
/**
 * Display name for the feature
 */
name: string, 
/**
 * Prefix used in IDs (e.g., "AUTH" for Authentication)
 */
prefix: string, 
/**
 * Optional description
 */
description: string, };

export type IdConfiguration = { 
/**
 * Format style for IDs
 */
format: IdFormat, 
/**
 * Numbering strategy
 */
numbering: NumberingStrategy, 
/**
 * Number of digits for the numeric portion (default 3 = 001)
 */
digits: number, 
/**
 * Configured requirement types
 */
requirement_types: Array<RequirementTypeDefinition>, };

export type RelationshipValidation = { 
/**
 * Whether the relationship is valid
 */
valid: boolean, 
/**
 * Error messages (if invalid)
 */
errors: Array<string>, 
/**
 * Warning messages (valid but may have issues)
 */
warnings: Array<string>, };

export type Relationship = { 
/**
 * The type of relationship
 */
rel_type: RelationshipType, 
/**
 * The target requirement ID
 */
target_id: string, 
/**
 * When this relationship was created
 */
created_at?: string | null, 
/**
 * Who created this relationship
 */
created_by?: string | null, };

export type FieldChange = { 
/**
 * Name of the field that changed
 */
field_name: string, 
/**
 * Value before the change
 */
old_value: string, 
/**
 * Value after the change
 */
new_value: string, };

export type HistoryEntry = { 
/**
 * Unique identifier for this history entry
 */
id: string, 
/**
 * Who made the change
 */
author: string, 
/**
 * When the change was made
 */
timestamp: string, 
/**
 * List of field changes in this update
 */
changes: Array<FieldChange>, };

export type ReactionDefinition = { 
/**
 * Unique identifier/key for the reaction (e.g., "resolved", "rejected")
 */
name: string, 
/**
 * The emoji character to display
 */
emoji: string, 
/**
 * Human-readable label for the reaction
 */
label: string, 
/**
 * Optional description of when to use this reaction
 */
description: string | null, 
/**
 * Whether this is a built-in reaction (cannot be deleted)
 */
built_in: boolean, };

export type CommentReaction = { 
/**
 * The reaction type (references ReactionDefinition.name)
 */
reaction: string, 
/**
 * Who added this reaction
 */
author: string, 
/**
 * When the reaction was added
 */
added_at: string, };

export type UrlOpenMode = "preview" | "new_tab";

export type UrlLink = { 
/**
 * Unique identifier for the link
 */
id: string, 
/**
 * The URL
 */
url: string, 
/**
 * Display title/label for the link
 */
title: string, 
/**
 * Optional description
 */
description?: string | null, 
/**
 * How the URL should be opened (preview iframe or new tab)
 */
open_mode: UrlOpenMode, 
/**
 * When the link was added
 */
added_at: string, 
/**
 * Who added the link
 */
added_by: string, 
/**
 * Last time the URL was verified as accessible
 */
last_verified?: string | null, 
/**
 * Whether the last verification succeeded
 */
last_verified_ok?: boolean | null, };

export type Attachment = { 
/**
 * Unique identifier for the attachment
 */
id: string, 
/**
 * Original filename
 */
filename: string, 
/**
 * Relative path to the stored file (e.g., "attachments/FR-0042/document.pdf")
 */
stored_path: string, 
/**
 * Optional MIME type
 */
mime_type?: string | null, 
/**
 * File size in bytes
 */
size_bytes: bigint, 
/**
 * When the attachment was added
 */
added_at: string, 
/**
 * Who added the attachment (user handle)
 */
added_by?: string | null, 
/**
 * Optional description of the attachment
 */
description?: string | null, };

export type ArtifactType = "SourceCode" | "TestCode" | "Config" | "Doc";

export type TraceLink = { 
/**
 * Unique identifier for the trace link
 */
id: string, 
/**
 * The type of artifact (source, test, config, doc)
 */
artifact_type: ArtifactType, 
/**
 * Path to the file containing the artifact (relative to project root)
 */
file_path: string, 
/**
 * Optional symbol name (function, struct, module, etc.)
 */
symbol?: string | null, 
/**
 * Optional line range (start, end) where the implementation exists
 */
line_start?: number | null, line_end?: number | null, 
/**
 * Optional notes about this trace link
 */
notes?: string | null, 
/**
 * When this trace link was created
 */
created_at: string, 
/**
 * Who created this trace link
 */
created_by?: string | null, 
/**
 * Git commit hash where this trace was identified (optional)
 */
commit_hash?: string | null, };

export type GitLabLinkType = "ImplementedBy" | "TracesTo" | "RelatedBug" | "FollowUp";

export type GitLabIssueLink = { 
/**
 * Unique identifier for the link
 */
id: string, 
/**
 * GitLab issue IID (project-scoped issue number)
 */
issue_iid: bigint, 
/**
 * GitLab project ID (optional - uses default from config if not set)
 */
project_id?: bigint | null, 
/**
 * Display title for the issue (cached from GitLab)
 */
issue_title: string, 
/**
 * Type of link between requirement and issue
 */
link_type: GitLabLinkType, 
/**
 * Optional notes about this link
 */
notes?: string | null, 
/**
 * When this link was created
 */
created_at: string, 
/**
 * Who created this link
 */
created_by?: string | null, 
/**
 * Last time the issue data was synced from GitLab
 */
last_synced?: string | null, 
/**
 * GitLab issue state when last synced (open/closed)
 */
issue_state?: string | null, };

export type LinkOrigin = "CreatedFromAida" | "ImportedFromGitLab" | "ManualLink";

export type SyncStatus = "InSync" | "AidaModified" | "GitLabModified" | "Conflict" | "Error" | "Untracked";

export type GitLabSyncState = { 
/**
 * AIDA requirement UUID
 */
requirement_id: string, 
/**
 * AIDA spec-id (for display)
 */
spec_id: string, 
/**
 * GitLab project ID
 */
gitlab_project_id: bigint, 
/**
 * GitLab issue IID (project-scoped issue number)
 */
gitlab_issue_iid: bigint, 
/**
 * GitLab issue global ID (for API operations)
 */
gitlab_issue_id: bigint, 
/**
 * When the link was created
 */
linked_at: string, 
/**
 * Last successful sync timestamp
 */
last_sync: string, 
/**
 * Hash of AIDA content at last sync
 */
aida_content_hash: string, 
/**
 * Hash of GitLab content at last sync
 */
gitlab_content_hash: string, 
/**
 * How the link was created
 */
link_origin: LinkOrigin, 
/**
 * Current sync status
 */
sync_status: SyncStatus, 
/**
 * Last sync error message (if any)
 */
last_error?: string | null, };

export type ConfidenceLevel = "High" | "Medium" | "Low";

export type ImplementationInfo = { 
/**
 * Whether the requirement has been implemented
 */
implemented: boolean, 
/**
 * Summary of the implementation
 */
summary?: string | null, 
/**
 * When the last AI agent run occurred for this requirement
 */
last_agent_run?: string | null, 
/**
 * Risk notes identified during implementation
 */
risk_notes?: string | null, 
/**
 * Notes about test coverage
 */
test_coverage_notes?: string | null, 
/**
 * The AI tool used for implementation (e.g., "claude", "copilot")
 */
source_tool?: string | null, 
/**
 * Confidence level of the AI-generated implementation
 */
confidence?: ConfidenceLevel | null, 
/**
 * When the implementation was completed
 */
implemented_at?: string | null, 
/**
 * Who performed the implementation
 */
implemented_by?: string | null, 
/**
 * When the auto-bump from `Done` → `Completed` fired (i.e. when a
 * commit referencing this spec landed on the default branch).
 * Stamped by the `aida pull` auto-bump path, not by `aida queue done`.
 * trace:STORY-86 | ai:claude
 */
completed_at?: string | null, 
/**
 * The default-branch commit SHA that triggered the auto-bump.
 * Stamped alongside `completed_at`.
 * trace:STORY-86 | ai:claude
 */
completion_sha?: string | null, };

export type Comment = { 
/**
 * Unique identifier for the comment
 */
id: string, 
/**
 * Author of the comment
 */
author: string, 
/**
 * Content of the comment
 */
content: string, 
/**
 * When the comment was created
 */
created_at: string, 
/**
 * When the comment was last modified
 */
modified_at: string, 
/**
 * Parent comment ID (None for top-level comments)
 */
parent_id: string | null, 
/**
 * Nested replies to this comment
 */
replies?: Array<Comment>, 
/**
 * Reactions on this comment
 */
reactions?: Array<CommentReaction>, };

export type User = { 
/**
 * Unique identifier for the user
 */
id: string, 
/**
 * Human-friendly spec ID (e.g., "$USER-001")
 */
spec_id: string | null, 
/**
 * User's full name
 */
name: string, 
/**
 * User's email address
 */
email: string, 
/**
 * User's handle for @mentions (without the @)
 */
handle: string, 
/**
 * Hashed PIN for simple authentication (SHA-256 hash stored as hex string)
 * This is a basic authentication mechanism for web clients.
 * For production use, consider a proper auth system (OAuth, JWT, etc.)
 */
pin_hash?: string | null, 
/**
 * When the user was created
 */
created_at: string, 
/**
 * Whether the user is archived
 */
archived?: boolean, };

export type Team = { 
/**
 * Unique identifier for the team
 */
id: string, 
/**
 * Human-friendly spec ID (e.g., "$TEAM-001")
 */
spec_id: string | null, 
/**
 * Team name
 */
name: string, 
/**
 * Team description (optional)
 */
description?: string, 
/**
 * Parent team ID for nested teams (None if top-level team)
 */
parent_team_id: string | null, 
/**
 * User IDs of team members
 */
member_ids?: Array<string>, 
/**
 * When the team was created
 */
created_at: string, 
/**
 * When the team was last modified
 */
modified_at: string | null, 
/**
 * Whether the team is archived
 */
archived?: boolean, };

export type Requirement = { 
/**
 * Unique identifier for the requirement (UUID)
 */
id: string, 
/**
 * Human-friendly specification ID (e.g., "SPEC-001")
 */
spec_id: string | null, 
/**
 * Short agreed ID assigned at merge-to-trunk (e.g., "FR-423").
 * Only populated in distributed mode after the merge gate runs.
 * In centralized mode, spec_id is already the short form so this is unused.
 * Both spec_id and agreed_id permanently resolve to the same UUID.
 */
agreed_id?: string | null, 
/**
 * Optional prefix override for the spec_id (e.g., "SEC" for security requirements)
 * If set, uses this prefix instead of deriving from feature/type
 * Must be uppercase letters only (A-Z)
 */
prefix_override?: string | null, 
/**
 * Short title describing the requirement
 */
title: string, 
/**
 * Detailed description of the requirement
 */
description: string, 
/**
 * Current status of the requirement
 */
status: RequirementStatus, 
/**
 * Priority level of the requirement
 */
priority: RequirementPriority, 
/**
 * Person responsible for the requirement
 */
owner: string, 
/**
 * The feature this requirement belongs to
 */
feature: string, 
/**
 * When the requirement was created
 */
created_at: string, 
/**
 * Who created this requirement
 */
created_by?: string | null, 
/**
 * When the requirement was last modified
 */
modified_at: string, 
/**
 * Type of the requirement
 */
req_type: RequirementType, 
/**
 * Subtype for Meta requirements (prompts, skills, commands, etc.)
 */
meta_subtype?: MetaSubtype | null, 
/**
 * IDs of requirements this requirement depends on
 */
dependencies?: Array<string>, 
/**
 * Tags for categorizing the requirement
 */
tags?: Array<string>, 
/**
 * Weight/effort estimate for the requirement (e.g., story points)
 * Optional - only shown in UI when set
 */
weight?: number | null, 
/**
 * Relationships to other requirements
 */
relationships?: Array<Relationship>, 
/**
 * Comments on this requirement (threaded)
 */
comments?: Array<Comment>, 
/**
 * History of changes to this requirement
 */
history?: Array<HistoryEntry>, 
/**
 * Whether this requirement is archived
 */
archived?: boolean, 
/**
 * Timestamp when this requirement was archived (None when not archived).
 * Cleared on unarchive. Used by `aida archive --older-than` sweeps and
 * the auto-sweep on `aida pull` to compute spec age.
 * trace:STORY-441 | ai:claude
 */
archived_at?: string | null, 
/**
 * Custom status string (for types with custom statuses)
 * If set, this takes precedence over the `status` enum field
 */
custom_status?: string | null, 
/**
 * Custom priority string (for types with custom priorities)
 * If set, this takes precedence over the `priority` enum field
 */
custom_priority?: string | null, 
/**
 * Custom field values (key = field name, value = field value as string)
 */
custom_fields?: { [key in string]?: string }, 
/**
 * External URL links attached to this requirement
 */
urls?: Array<UrlLink>, 
/**
 * File attachments on this requirement
 */
attachments?: Array<Attachment>, 
/**
 * Trace links to code artifacts implementing this requirement
 */
trace_links?: Array<TraceLink>, 
/**
 * Links to GitLab issues related to this requirement
 */
gitlab_issues?: Array<GitLabIssueLink>, 
/**
 * Implementation metadata for this requirement
 */
implementation_info?: ImplementationInfo | null, 
/**
 * Cached AI evaluation results
 * Automatically populated by background evaluator when requirement changes
 */
ai_evaluation?: StoredAiEvaluation | null, 
/**
 * Why this spec is paused — set by `aida punt` when status flips to
 * `NeedsAttention`, cleared when it is triaged back out. Answers "why is
 * this *currently* paused"; the punt ledger keeps the durable history.
 * trace:STORY-332 | ai:claude
 */
attention_reason?: AttentionReason | null, 
/**
 * Set by the `--auto-complete` orchestrator when it shelves a spec
 * after a phase failure (sibling to `attention_reason` — see
 * [`FailureReason`]). Sticks until the spec is triaged out of
 * `NeedsAttention`; the punt ledger keeps the durable history.
 * trace:EPIC-28 | ai:claude
 */
failure_reason?: FailureReason | null, 
/**
 * Marks this spec as work no agent can do — a person-in-the-room task,
 * a sign-off, a physical activity. The pre-pickup gate
 * (`crate::pickability`) skips any spec with this flag set so the
 * orchestrator/queue never spawn a doomed phase-1 implementer on it.
 * Distinct from `BlockedBy` (which clears when the blocker ships):
 * `human_only` is a permanent property of the spec, cleared only by
 * the human explicitly flipping it off. trace:STORY-333 | ai:claude
 */
human_only?: boolean, 
/**
 * A structured decision the human answers OUTSIDE any agent — the
 * async decision-inbox artifact. `None` when no question is pending or
 * recorded. Set by `aida questions ask`, answered by
 * `aida questions answer`. trace:STORY-522 | ai:claude
 */
decision_request?: DecisionRequest | null, };

export type RequirementSnapshot = { 
/**
 * The original requirement's UUID (for linking back)
 */
original_id: string, 
/**
 * Spec ID at the time of snapshot
 */
spec_id: string | null, 
/**
 * Title at snapshot time
 */
title: string, 
/**
 * Description at snapshot time
 */
description: string, 
/**
 * Status at snapshot time
 */
status: RequirementStatus, 
/**
 * Priority at snapshot time
 */
priority: RequirementPriority, 
/**
 * Owner at snapshot time
 */
owner: string, 
/**
 * Feature at snapshot time
 */
feature: string, 
/**
 * Type at snapshot time
 */
req_type: RequirementType, 
/**
 * Tags at snapshot time
 */
tags: Array<string>, 
/**
 * Relationships at snapshot time (storing IDs, not full objects)
 */
relationships: Array<Relationship>, 
/**
 * Custom status at snapshot time
 */
custom_status?: string | null, 
/**
 * Custom priority at snapshot time
 */
custom_priority?: string | null, 
/**
 * Custom fields at snapshot time
 */
custom_fields?: { [key in string]?: string }, };

export type Baseline = { 
/**
 * Unique identifier for this baseline
 */
id: string, 
/**
 * Human-readable name (e.g., "Release 1.0", "Sprint 5 End")
 */
name: string, 
/**
 * Optional description of what this baseline represents
 */
description?: string | null, 
/**
 * When the baseline was created
 */
created_at: string, 
/**
 * Who created the baseline
 */
created_by: string, 
/**
 * Git tag associated with this baseline (for YAML backend)
 * Format: "baseline-{name-slug}" or custom
 */
git_tag?: string | null, 
/**
 * Full snapshots of all requirements at baseline time
 * For SQL backends, this is always populated
 * For YAML backend, this may be empty if git_tag is used (can reconstruct from git)
 */
requirements?: Array<RequirementSnapshot>, 
/**
 * Whether this baseline is locked (cannot be modified or deleted)
 */
locked: boolean, };

export type BaselineComparison = { 
/**
 * Requirements added (in target but not in source)
 */
added: Array<string>, 
/**
 * Requirements removed (in source but not in target)
 */
removed: Array<string>, 
/**
 * Requirements modified (exist in both but changed)
 */
modified: Array<BaselineRequirementDiff>, 
/**
 * Requirements unchanged
 */
unchanged: Array<string>, };

export type BaselineRequirementDiff = { 
/**
 * The requirement's UUID
 */
id: string, 
/**
 * Spec ID (for display)
 */
spec_id: string | null, 
/**
 * List of changed fields
 */
changes: Array<FieldChange>, };

export type AiActionPromptConfig = { 
/**
 * Custom template to replace the default prompt entirely.
 * Use placeholders: {project_context}, {req_context}, {related_context}, {all_reqs}
 */
custom_template?: string | null, 
/**
 * Additional instructions appended to the default prompt.
 * Used when custom_template is None.
 */
additional_instructions?: string, };

export type AiTypePromptConfig = { 
/**
 * The requirement type this config applies to (e.g., "Functional", "Epic", "Story")
 */
type_name: string, 
/**
 * Extra instructions for evaluation prompts for this type
 */
evaluation_extra?: string, 
/**
 * Extra instructions for improve description prompts for this type
 */
improve_extra?: string, 
/**
 * Extra instructions for generate children prompts for this type
 */
generate_children_extra?: string, };

export type AiPromptConfig = { 
/**
 * Global context prepended to ALL AI prompts.
 * Use this to describe your project's methodology, terminology, or special rules.
 */
global_context?: string, 
/**
 * Configuration for the evaluation action
 */
evaluation?: AiActionPromptConfig, 
/**
 * Configuration for the find duplicates action
 */
duplicates?: AiActionPromptConfig, 
/**
 * Configuration for the suggest relationships action
 */
relationships?: AiActionPromptConfig, 
/**
 * Configuration for the improve description action
 */
improve?: AiActionPromptConfig, 
/**
 * Configuration for the generate children action
 */
generate_children?: AiActionPromptConfig, 
/**
 * Per-type customization
 */
type_prompts?: Array<AiTypePromptConfig>, };

export type RequirementsStore = { 
/**
 * Database name (displayed in window title prefix)
 */
name: string, 
/**
 * Database title (one-liner, displayed in window title)
 */
title: string, 
/**
 * Database description (multi-line)
 */
description: string, requirements: Array<Requirement>, 
/**
 * Users in the system
 */
users?: Array<User>, 
/**
 * Teams in the system
 */
teams?: Array<Team>, 
/**
 * ID system configuration
 */
id_config: IdConfiguration, 
/**
 * Defined features with their prefixes
 */
features: Array<FeatureDefinition>, 
/**
 * Counter for feature numbers (used when creating new features)
 */
next_feature_number: number, 
/**
 * Global counter for requirement IDs (used with Global numbering strategy)
 */
next_spec_number: number, 
/**
 * Per-prefix counters for requirement IDs (used with PerPrefix numbering)
 * Key is the prefix (e.g., "FR", "AUTH"), value is the next number
 */
prefix_counters: { [key in string]?: number }, 
/**
 * Relationship type definitions with constraints
 */
relationship_definitions: Array<RelationshipDefinition>, 
/**
 * Reaction definitions for comments
 */
reaction_definitions: Array<ReactionDefinition>, 
/**
 * Counter for meta-type IDs (users, views, etc.) - maps prefix to next number
 * e.g., "$USER" -> 1 means next user will be $USER-001
 */
meta_counters: { [key in string]?: number }, 
/**
 * Custom type definitions with their statuses and fields
 */
type_definitions: Array<CustomTypeDefinition>, 
/**
 * List of allowed/known ID prefixes for the project
 * These are collected from usage and can be managed by admins
 */
allowed_prefixes: Array<string>, 
/**
 * Whether to restrict prefix selection to only allowed_prefixes
 * When false, users can enter any valid prefix (which gets added to allowed_prefixes)
 * When true, users must select from the allowed_prefixes list
 */
restrict_prefixes: boolean, 
/**
 * AI prompt configuration for customizing AI behavior
 */
ai_prompts?: AiPromptConfig, 
/**
 * Baselines - named snapshots of requirements at specific points in time
 */
baselines?: Array<Baseline>, 
/**
 * Migration marker - if set, indicates this YAML was migrated to another format
 * Contains the path to the migrated database (e.g., "requirements.db")
 * When this is set, opening the YAML should warn/redirect to the migrated database
 */
migrated_to?: string | null, };

export type IssueReport = { type: string, severity: string, text: string, suggestion: string, };

export type SuggestedImprovement = { description: string | null, rationale: string, };

export type EvaluationResponse = { quality_score: number, issues: Array<IssueReport>, strengths: Array<string>, suggested_improvements: SuggestedImprovement | null, };

export type StoredAiEvaluation = { 
/**
 * The evaluation results from AI
 */
evaluation: EvaluationResponse, 
/**
 * When the evaluation was performed
 */
evaluated_at: string, 
/**
 * Hash of the requirement content at time of evaluation
 * Used to detect if requirement has changed since evaluation
 */
content_hash: string, };

export type DuplicateResult = { spec_id: string, similarity: number, reason: string, recommendation: string, };

export type DuplicatesResponse = { potential_duplicates: Array<DuplicateResult>, };

export type RelationshipSuggestion = { rel_type: string, target_spec_id: string, confidence: number, rationale: string, };

export type SuggestRelationshipsResponse = { suggested_relationships: Array<RelationshipSuggestion>, };

export type ImproveDescriptionResponse = { improved_description: string, changes_made: Array<string>, rationale: string, };

export type GeneratedChild = { title: string, description: string, type: string, rationale: string, };

export type GenerateChildrenResponse = { suggested_children: Array<GeneratedChild>, };

export type QueueEntry = {
    requirementId: string;
    specId: string | null;
    title: string;
    status: string;
    priority: string;
    reqType: string;
    position: number;
    addedBy: string;
    note: string | null;
    addedAt: string;
};