#!/usr/bin/env python3
"""Enumerate declared production classifiers over external-tool prose.

Predicate: a classifier is a production Rust decision site carrying a line
comment of the exact form `// external-prose-classifier: <site>`.  Generated
files, tests, fixtures, and prose without that marker deliberately do not
count.  This marker-based predicate is intentionally syntactic: inferring
whether an arbitrary string comparison consumes external output is not
decidable from Rust syntax alone.  Review must require the marker when adding
such a decision; this checker then makes additions and documentation drift
mechanically visible.

trace:TASK-1300 | ai:codex
"""

from __future__ import annotations

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
DOC = ROOT / "docs/architecture/external-tool-output-classifiers.md"
MARKER = re.compile(r"^\s*// external-prose-classifier: ([A-Za-z0-9_:{}-]+)\s*$")


def enumerate_sites(root: pathlib.Path) -> list[tuple[str, str, int]]:
    found: list[tuple[str, str, int]] = []
    for path in sorted(root.glob("aida-*/src/**/*.rs")):
        for line_no, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            match = MARKER.match(line)
            if match:
                found.append((match.group(1), path.relative_to(root).as_posix(), line_no))
    names = [row[0] for row in found]
    duplicates = sorted({name for name in names if names.count(name) > 1})
    if duplicates:
        raise ValueError(f"duplicate classifier marker(s): {', '.join(duplicates)}")
    return sorted(found)


def render(rows: list[tuple[str, str, int]]) -> str:
    body = [
        "# External-tool output classifiers",
        "",
        "<!-- Generated by scripts/external-prose-classifiers.py; do not edit by hand. -->",
        "",
        "A production classifier is enumerated when its Rust decision site carries",
        "`// external-prose-classifier: <site>`. Tests, fixtures, generated files, and",
        "unmarked string comparisons deliberately do not count. The marker is the precise",
        "boundary because Rust syntax cannot reveal whether an arbitrary string came from",
        "an external process; code review must require it for every new such decision.",
        "",
        "| Site | Source |",
        "|---|---|",
    ]
    # BUG-1526: the row is name + PATH and deliberately omits the line number.
    # A required gate that compares line numbers byte-for-byte fires on any edit
    # ABOVE a marked site, with no classifier added, removed or renamed — eleven
    # open PRs were red for that reason and each lost its whole test suite,
    # because this step sits ahead of them and `bash -e` aborts the job.
    # CLAUDE.md already states the rule this gate was breaking: "Symbol refs over
    # line refs ... line refs drift fast and are often stale within hours".
    # The line is still printed on stdout below, where it is a navigation
    # convenience and nothing depends on it.
    # trace:BUG-1526 | ai:claude
    body.extend(f"| `{name}` | `{path}` |" for name, path, _line in rows)
    body.extend(["", "<!-- trace:TASK-1300 | ai:codex -->", ""])
    return "\n".join(body)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if the generated doc is stale")
    parser.add_argument("--root", type=pathlib.Path, default=ROOT, help=argparse.SUPPRESS)
    args = parser.parse_args()
    root = args.root.resolve()
    try:
        rows = enumerate_sites(root)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    if not rows:
        print("error: no external-prose classifier markers found", file=sys.stderr)
        return 1
    rendered = render(rows)
    doc = root / DOC.relative_to(ROOT)
    if args.check:
        current = doc.read_text(encoding="utf-8") if doc.exists() else ""
        if current != rendered:
            # BUG-1526 criterion 3: name what actually changed. The old message
            # said only "is stale", which reads as a real inventory change and
            # sent reviewers to re-derive a diff the checker already knows.
            # Since criterion 1 removed line numbers from the comparison, a
            # difference here IS a set change — drift alone can no longer
            # produce one.
            # trace:BUG-1526 | ai:claude
            def sites(text: str) -> set[str]:
                return {
                    line.split("|")[1].strip().strip("`")
                    for line in text.splitlines()
                    if line.startswith("| `")
                }

            added = sorted(sites(rendered) - sites(current))
            removed = sorted(sites(current) - sites(rendered))
            print(f"error: {doc.relative_to(root)} does not match the markers in the tree", file=sys.stderr)
            if added:
                print(f"  added:   {', '.join(added)}", file=sys.stderr)
            if removed:
                print(f"  removed: {', '.join(removed)}", file=sys.stderr)
            if not added and not removed:
                print("  the classifier set is unchanged; only surrounding text differs", file=sys.stderr)
            print(f"  regenerate with a bare run: python3 {pathlib.Path(__file__).name}", file=sys.stderr)
            return 1
    else:
        doc.write_text(rendered, encoding="utf-8")
    for name, path, line in rows:
        print(f"{name}\t{path}:{line}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
