#!/usr/bin/env python3
"""Regenerate the exhaustive global --format json command audit.

The command catalog is clap-derived, so this inventory cannot silently omit a
new leaf. Verification is intentionally conservative: only invocations driven
by the end-to-end conformance test are labelled honoured; JSON-capable leaves
that require external state, destructive input, or credentials remain
COULD NOT VERIFY rather than being misreported as failures.
"""

from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


VERIFIED = {
    "aida fasttrack status": "fasttrack status",
    "aida show": "show <SPEC> --no-git",
    "aida list": "list --limit 1",
    "aida status": "status <SPEC>",
    "aida ps": "ps",
    "aida queue": "queue (compatibility alias to queue list)",
    "aida queue list": "queue list",
    "aida queue progress": "queue progress",
    "aida findings list": "findings list",
}


def main() -> int:
    if len(sys.argv) != 3:
        print("usage: generate-format-json-audit.py AIDA_BINARY OUTPUT", file=sys.stderr)
        return 2
    binary, output = sys.argv[1], Path(sys.argv[2])
    # Hidden/deprecated/substrate leaves accept the global flag too; include
    # them so the audit cannot hide a fallback behind catalog visibility.
    raw = subprocess.check_output(
        [binary, "help", "commands", "--json", "--hidden"], text=True
    )
    catalog = json.loads(raw)
    rows = []
    for entry in catalog:
        path = " ".join(entry["path"])
        has_json = any(flag.get("name") == "json" for flag in entry.get("flags", []))
        if path in VERIFIED:
            outcome = "JSON honoured"
            probe = VERIFIED[path]
        elif has_json:
            outcome = "COULD NOT VERIFY"
            probe = "Dedicated --json exists; needs command-specific state or external service"
        else:
            outcome = "JSON not honoured"
            probe = "Explicitly rejected before dispatch (no local --json contract)"
        rows.append((path, outcome, probe))

    lines = [
        "# `--format json` conformance audit",
        "",
        "<!-- generated by scripts/generate-format-json-audit.py; trace:BUG-1502 -->",
        "",
        "`--format` is a global clap option, so every command path below accepts it",
        "syntactically. A command honours JSON only when its selected leaf declares a",
        "dedicated `--json` projection. The runtime rejects all other leaves before",
        "dispatch; they can never silently fall back to human or TOON output.",
        "",
        "`--format json` and `--json` are one contract and must emit the same JSON",
        "document wherever both spellings exist. `JSON honoured` rows are executed by",
        "the BUG-1502 end-to-end test. `COULD NOT VERIFY` is deliberately distinct from",
        "failure: the leaf declares JSON, but its invocation needs destructive input,",
        "credentials, live processes, or another external condition not available to the",
        "hermetic audit. `JSON not honoured` means unsupported and explicitly rejected.",
        "",
        "| Command | Outcome | Probe / disposition |",
        "|---|---|---|",
    ]
    lines.extend(f"| `{path}` | {outcome} | {probe} |" for path, outcome, probe in rows)
    output.write_text("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
